"""Frozen path and policy catalog for historical render-build manifest V1."""

from __future__ import annotations

RENDER_BUILD_V1_POLICY = "sniper-headless-render-build-v2"
RENDER_BUILD_V1_DIGEST_DOMAIN = b"sniper-render-build-v2\0"
RENDER_BUILD_V1_IMPLEMENTATION_PATHS = (
    "scripts/producer/fingerprints.py",
    "scripts/producer/producer_config.py",
    "scripts/producer/graphics/__init__.py",
    "scripts/producer/graphics/asset_proof.py",
    "scripts/producer/graphics/composition_transform.py",
    "scripts/producer/graphics/frame_oracles.py",
    "scripts/producer/graphics/graphics_render.py",
    "scripts/producer/graphics/pip_hole.py",
    "scripts/producer/graphics/pip_takeover.py",
    "scripts/producer/graphics/render_cache.py",
    "scripts/producer/graphics/render_tools.py",
    "scripts/producer/graphics/sealed_graphics_render.py",
    "scripts/producer/graphics/template_assets.py",
    "scripts/producer/graphics/template_content.py",
    "scripts/producer/graphics/template_contract.py",
    "scripts/producer/graphics/template_visual_contract.py",
    "scripts/producer/headless/__init__.py",
    "scripts/producer/headless/admission_lookup.py",
    "scripts/producer/headless/admission_record.py",
    "scripts/producer/headless/admission_registry.py",
    "scripts/producer/headless/admitted_render_lane.py",
    "scripts/producer/headless/attempt_trace.py",
    "scripts/producer/headless/attempt_initialization.py",
    "scripts/producer/headless/authority_record.py",
    "scripts/producer/headless/boot_identity.py",
    "scripts/producer/headless/container_io.py",
    "scripts/producer/headless/container_live_policy.py",
    "scripts/producer/headless/container_policy.py",
    "scripts/producer/headless/container_renderer.py",
    "scripts/producer/headless/controller_ownership.py",
    "scripts/producer/headless/docker_identity.py",
    "scripts/producer/headless/durable_files.py",
    "scripts/producer/headless/durability_controller.py",
    "scripts/producer/headless/network_probe.py",
    "scripts/producer/headless/overlay_seal_store.py",
    "scripts/producer/headless/process_runner.py",
    "scripts/producer/headless/request_artifact.py",
    "scripts/producer/headless/render_admission_artifact.py",
    "scripts/producer/headless/render_admission_artifact_reader.py",
    "scripts/producer/headless/render_admission_schema.py",
    "scripts/producer/headless/render_admission.py",
    "scripts/producer/headless/render_build.py",
    "scripts/producer/headless/render_build_manifest_v1_contract.py",
    "scripts/producer/headless/render_build_receipt.py",
    "scripts/producer/headless/render_image_approval.json",
    "scripts/producer/headless/render_lane.py",
    "scripts/producer/headless/render_lane_cache.py",
    "scripts/producer/headless/render_result.py",
    "scripts/producer/headless/render_runtime.py",
    "scripts/producer/headless/render_worker.py",
    "scripts/producer/headless/render_worker_bootstrap.py",
    "scripts/producer/headless/resource_ledger.py",
    "scripts/producer/headless/runtime_receipt.py",
    "scripts/producer/headless/sealed_archive.py",
    "scripts/producer/headless/sealed_tar_format.py",
    "scripts/producer/headless/safe_source_files.py",
    "scripts/producer/headless/source_closure.py",
    "scripts/producer/headless/terminal_intent.py",
    "scripts/producer/headless/terminal_manifest.py",
    "scripts/producer/headless/trace_frames.py",
    "scripts/producer/headless/trace_state.py",
    "scripts/producer/headless/overlay_seal.py",
    "scripts/producer/headless/overlay_source_seal.py",
)
