import assert from "node:assert/strict";
import { test } from "node:test";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import GuidedOpeningPanel, { GuidedOpeningContent } from "@/components/producer/guided-opening-panel";
import { GUIDED_OPENING_STATUS_SCOPE, type GuidedOpeningStatusV1 } from "../contracts/guided-opening-status-v1";
import { fetchGuidedOpeningStatus, parseGuidedOpeningStatus } from "../guided-opening-client";
import { openingPlaybackMatches } from "../guided-opening-media-client";

Object.assign(globalThis, { React });
const openingDir = "/private/tmp/synthetic-opening-ui/producer";
const mediaHash = "1".repeat(64), selectionHash = "2".repeat(64);
const origin = "2026-09-06T00:01:00.000Z";
const identity = { requestId: "11111111-1111-4111-8111-111111111111",
  executionId: "22222222-2222-4222-8222-222222222222", claimHash: "3".repeat(64) };
const unavailableTiming = { generationStartedAt: origin, engineElapsedMs: null, cleanupElapsedMs: null,
  elapsedStatus: "unavailable", coverage: "unavailable" } as const;

function media(range: "core" | "review", videoFrames: number) {
  return { url: `/api/producer/guided-opening/media?${new URLSearchParams({ dir: openingDir, selectionHash,
    mediaSha256: mediaHash, range })}`, mediaSha256: mediaHash, sizeBytes: 123_456, width: 1920, height: 1080,
  frameRate: "30000/1001", videoFrames, startFrame: 0, endFrameExclusive: videoFrames, audioSamples: videoFrames * 1601.6 };
}

/** Display-only fixture, never input to any server approval or media selection. */
function readyOpening(): Extract<GuidedOpeningStatusV1, { state: "ready-for-review" }> {
  return { ok: true, schemaVersion: 1, scope: GUIDED_OPENING_STATUS_SCOPE, state: "ready-for-review", ...identity,
    openingApproved: false, deliveryApproved: false, subjectiveListening: "not-performed-by-system",
    detail: "Synthetic UI-only description. No real opening was generated by this fixture.",
    timing: { generationStartedAt: origin, engineElapsedMs: 60_000, cleanupElapsedMs: 1250,
      elapsedStatus: "completed", coverage: "recorded-owned-attempt-only" },
    selectionHash, receiptHash: "4".repeat(64), receiptSha256: "5".repeat(64),
    selectionQualifiedAt: "2026-09-06T00:02:01.250Z", sourceFreshness: "not-rechecked-by-status",
    journal: { token: "guided-job", sha256: "7".repeat(64) }, approval: null,
    media: { core: media("core", 300), review: media("review", 450) } };
}

function pendingOpening(state: "unavailable" | "pending-owned-execution" | "pending-cleanup" | "failed"): GuidedOpeningStatusV1 {
  const { selectionHash: _selection, receiptHash: _receipt, receiptSha256: _raw, media: _media,
    selectionQualifiedAt: _at, sourceFreshness: _freshness, journal: _journal, approval: _approval, ...base } = readyOpening();
  void _journal; void _approval;
  void _selection; void _receipt; void _raw; void _media; void _at; void _freshness;
  return { ...base, state, timing: state === "pending-owned-execution" || state === "unavailable" ? unavailableTiming : base.timing };
}

test("opening display parser accepts exact read-only states and selection URLs", () => {
  const ready = readyOpening(); assert.deepEqual(parseGuidedOpeningStatus(ready, openingDir), ready);
  for (const state of ["unavailable", "pending-owned-execution", "pending-cleanup", "failed"] as const) {
    const pending = pendingOpening(state); assert.deepEqual(parseGuidedOpeningStatus(pending, openingDir), pending);
    assert.throws(() => parseGuidedOpeningStatus({ ...pending, media: ready.media }, openingDir));
  }
  const missing = { ...pendingOpening("unavailable"), requestId: null, executionId: null, claimHash: null };
  assert.deepEqual(parseGuidedOpeningStatus(missing, openingDir), missing);
});

test("opening parser cannot accept approval, hidden capabilities, foreign identity or invented time", () => {
  const ready = readyOpening();
  for (const patch of [{ ok: false }, { schemaVersion: 2 }, { scope: "approved-final" }, { state: "finished" },
    { openingApproved: true }, { deliveryApproved: true }, { subjectiveListening: "passed" }, { extra: 1 },
    { requestId: null }, { executionId: "other" }, { claimHash: "x" }, { selectionHash: "x" }, { receiptHash: "x" },
    { receiptSha256: "x" }, { detail: "" }, { detail: "x".repeat(2049) }, { sourceFreshness: "current" },
    { selectionQualifiedAt: "2026-09-06" }, { selectionQualifiedAt: "2020-01-01T00:00:00.000Z" }]) {
    assert.throws(() => parseGuidedOpeningStatus({ ...ready, ...patch }, openingDir));
  }
  for (const patch of [{ elapsedStatus: "active" }, { engineElapsedMs: -1 }, { engineElapsedMs: Infinity },
    { engineElapsedMs: null }, { cleanupElapsedMs: null }, { generationStartedAt: null },
    { generationStartedAt: "2026-09-06" }, { coverage: "whole-video" }, { elapsedStatus: "unavailable" }]) {
    assert.throws(() => parseGuidedOpeningStatus({ ...ready, timing: { ...ready.timing, ...patch } }, openingDir));
  }
  assert.throws(() => parseGuidedOpeningStatus({ ...pendingOpening("pending-owned-execution"), timing: ready.timing }, openingDir));
  assert.throws(() => parseGuidedOpeningStatus({ ...pendingOpening("unavailable"), requestId: null }, openingDir));
});

test("opening media clocks, context, and URL parameters remain exact", () => {
  const ready = readyOpening(), core = ready.media.core;
  for (const patch of [{ width: 0 }, { height: 16_385 }, { videoFrames: 299 }, { startFrame: 1 },
    { sizeBytes: 0 }, { audioSamples: core.audioSamples + 1 }, { frameRate: "30" }, { frameRate: "60000/2002" },
    { frameRate: "0/1" }, { frameRate: "61/1" }, { frameRate: "30000/1001/1" }, { frameRate: "030/1" },
    { endFrameExclusive: 72_001 }, { extra: 1 }, { url: "https://untrusted.example/video.mp4" },
    { url: `${core.url}&path=/etc/passwd` }, { url: `${core.url}#fragment` },
    { url: `${core.url}&range=core` }, { url: core.url.replace("range=core", "range=review") }]) {
    assert.throws(() => parseGuidedOpeningStatus({ ...ready, media: { ...ready.media, core: { ...core, ...patch } } }, openingDir));
  }
  assert.throws(() => parseGuidedOpeningStatus(ready, "/another/project"));
  assert.throws(() => parseGuidedOpeningStatus({ ...ready, media: { ...ready.media, extra: {} } }, openingDir));
  const shorter = { ...media("review", 150) };
  assert.throws(() => parseGuidedOpeningStatus({ ...ready, media: { core, review: shorter } }, openingDir));
});

test("exact audio boundary uses ties-to-even rather than rounded decimal seconds", () => {
  const ready = readyOpening();
  const core = { ...ready.media.core, frameRate: "32000/1001", videoFrames: 1, endFrameExclusive: 1, audioSamples: 1502 };
  const review = { ...ready.media.review, frameRate: "32000/1001", videoFrames: 3, endFrameExclusive: 3, audioSamples: 4504 };
  parseGuidedOpeningStatus({ ...ready, media: { core, review } }, openingDir);
  assert.throws(() => parseGuidedOpeningStatus({ ...ready, media: { core, review: { ...review, audioSamples: 4505 } } }, openingDir));
});

test("browser metadata check distinguishes missing/foreign playback, never a review decision", () => {
  const core = readyOpening().media.core;
  assert.equal(openingPlaybackMatches(core, { duration: 10.01, width: 1920, height: 1080 }), true);
  for (const patch of [{ duration: NaN }, { duration: Infinity }, { duration: 9 }, { width: 1080 }, { height: 1920 }]) {
    assert.equal(openingPlaybackMatches(core, { duration: 10.01, width: 1920, height: 1080, ...patch }), false);
  }
});

test("opening status fetch is bounded, abortable, no-store and read-only without retry", async () => {
  let calls = 0;
  const request: typeof fetch = async (url, init) => {
    calls++; assert.equal(String(url), `/api/producer/guided-opening/status?${new URLSearchParams({ dir: openingDir })}`);
    assert.equal(init?.method, undefined); assert.equal(init?.cache, "no-store"); assert.equal(init?.redirect, "error");
    return Response.json(readyOpening());
  };
  assert.deepEqual(await fetchGuidedOpeningStatus(openingDir, new AbortController().signal, request), readyOpening());
  const aborted = new AbortController(); aborted.abort();
  await assert.rejects(fetchGuidedOpeningStatus(openingDir, aborted.signal, request), { name: "AbortError" });
  assert.equal(calls, 1);
  await assert.rejects(fetchGuidedOpeningStatus(openingDir, new AbortController().signal,
    async () => new Response("x".repeat(16_385))), /Opening status.*size limit/);
  await assert.rejects(fetchGuidedOpeningStatus(openingDir, new AbortController().signal,
    async () => Response.json({ error: "Opening source changed" }, { status: 409 })), /source changed/);
  await assert.rejects(fetchGuidedOpeningStatus(openingDir, new AbortController().signal,
    async () => Response.json({ ...readyOpening(), openingApproved: true })), /approval/);
});

test("initial opening panel exposes no media or premature launch/review controls", () => {
  const html = renderToStaticMarkup(React.createElement(GuidedOpeningPanel, { dir: openingDir }));
  assert.match(html, /HyperFrames opening review/); assert.match(html, /Checking opening state/);
  assert.match(html, /Recheck opening evidence/);
  assert.match(html, /Checking opening launch eligibility/);
  assert.doesNotMatch(html, /<video|<iframe|<form|>Generate opening<|>Approve|>Resume/);
  assert.doesNotMatch(html, /This view is read-only/);
});

test("all nonselectable states have no video, no success claim and no automatic retry", () => {
  for (const state of ["unavailable", "pending-owned-execution", "pending-cleanup", "failed"] as const) {
    const html = renderToStaticMarkup(React.createElement(GuidedOpeningContent, { opening: pendingOpening(state) }));
    assert.doesNotMatch(html, /<video|<iframe|<button|<form|QC passed|Approved delivery/);
    assert.match(html, /No opening or delivery approval/);
    assert.match(html, /Subjective listening has not been performed/);
    assert.match(html, /not a completion estimate/);
  }
  const pending = renderToStaticMarkup(React.createElement(GuidedOpeningContent, { opening: pendingOpening("pending-owned-execution") }));
  assert.match(pending, /does not prove a worker is running/); assert.match(pending, /Unknown time is not zero/);
  assert.match(pending, /Do not start a duplicate render/);
  assert.doesNotMatch(pending, /Owned attempt to verified stop/);
});

test("ready display defaults to context playback and reports only the recorded attempt", () => {
  const html = renderToStaticMarkup(React.createElement(GuidedOpeningContent, { opening: readyOpening() }));
  assert.equal((html.match(/<video /g) ?? []).length, 1);
  assert.match(html, /range=review/); assert.match(html, /Opening \+ context/);
  assert.match(html, /unapproved opening preview/); assert.match(html, /Opening available for review/);
  assert.match(html, /Owned attempt to verified stop: 1m 0s/); assert.match(html, /Separate resource cleanup: 1s/);
  assert.match(html, /Earlier cut, proposal and review work are not included/);
  assert.match(html, /This status has not rechecked source bytes/);
  assert.match(html, /Opening approval requires the separate explicit review checklist/);
  assert.match(html, /Scoped revision and full-video continuation are still unfinished/);
  assert.doesNotMatch(html, /autoPlay|autoplay|muted|<form|>Approve|>Generate|QC passed|finished video/);
});

test("a verified operator approval is displayed without claiming body or delivery approval", () => {
  const opening = { ...readyOpening(), openingApproved: true as const,
    approval: { approvalHash: "a".repeat(64), approvedAt: "2026-09-06T00:03:00.000Z", decisionHash: "b".repeat(64) } };
  const html = renderToStaticMarkup(React.createElement(GuidedOpeningContent, { opening }));
  assert.match(html, /Opening approved by operator · body pending/);
  assert.match(html, /operator-approved opening preview/);
  assert.match(html, /No body or delivery approval/);
  assert.doesNotMatch(html, /Opening available for review · not approved|unapproved opening preview|Human review recording.*not enabled/);
});

test("server detail remains escaped plain text rather than interactive injected markup", () => {
  const opening = { ...pendingOpening("failed"), detail: '<img src="https://untrusted.example/pixel" onerror="go()">' };
  const html = renderToStaticMarkup(React.createElement(GuidedOpeningContent, { opening }));
  assert.match(html, /&lt;img/); assert.doesNotMatch(html, /<img/);
});
