"""Generate current ordinary-plan moving previews before final render approval.

Run after mint-delivery-approval.ts --draft. Cold runs prepare the full ordinary
base/master; revisions reuse proved preparation and unchanged context clips.
No review, final readiness or delivery approval is generated by this command.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

from cut_preview_io import bound_json, digest, write_new
from ordinary_preview_windows import preview_windows, window_key
from readiness_preview import observe_preview, verify_preview
from render_readiness import ReadinessRequest, readiness_packet, require_readiness
from studio.owned_inspection import read_inspection, require_worker, run_inspection
from studio.native_stage_evidence import require

HERE = Path(__file__).resolve()


def _readiness(request: dict) -> ReadinessRequest:
    """Preview admission is separate from full final approval."""
    return ReadinessRequest(request["planPath"], request["manifestPath"], request["project"], draft=True)


def _current(request: dict) -> None:
    """Bind canonical inputs before/after media without minting final readiness."""
    require_readiness(_readiness(request))
    require(readiness_packet(_readiness(request)) == request["packet"], "Ordinary preview dependencies changed")
    require(bound_json(Path(request["planPath"])) == request["plan"]
            and bound_json(Path(request["manifestPath"])) == request["manifest"],
            "Ordinary preview documents changed")


def worker(file: Path) -> None:
    """Only the actual native supervisor can enter media preparation or composition."""
    from ordinary_preview_media import prepare, render_window
    request = require_worker(file, HERE)
    _current(request)
    root = file.parent
    if request["phase"] == "prepare":
        previous = read_inspection(request["previous"]) if request.get("previous") else None
        result = prepare(request, root, previous)
    elif request["phase"] == "window":
        prepared = read_inspection(request["preparation"])
        result = render_window(request, prepared, request["window"], root)
        result["admittedMedia"] = observe_preview(Path(result["path"]), root / "admitted-media")
        result["key"] = window_key(request["window"], request, prepared)
    else:
        raise ValueError("Unknown ordinary preview inspection phase")
    _current(request)
    require_worker(file, HERE)
    write_new(root / "result.json", result)


def prior_generation(file: Path, project: str) -> dict:
    """A previous generation must retain every original owner and actual media."""
    value = bound_json(file)
    body = {key: item for key, item in value.items() if key != "digest"}
    require(value.get("kind") == "ordinary-moving-previews" and value.get("status") == "complete"
            and value.get("project") == project and value.get("digest") == digest(body),
            "Prior ordinary previews are incomplete or belong to another project")
    read_inspection(value["preparation"])
    for row in value["clips"]:
        media = read_inspection(row["inspection"])
        require(media["key"] == row["key"], "Prior ordinary preview binding changed")
        verify_preview(media["admittedMedia"])
    return value


def _register(project: Path, window: dict, inspection: dict) -> dict:
    """Register fully decoded bytes under current review units, never an assessment."""
    media = read_inspection(inspection)
    verify_preview(media["admittedMedia"])
    core = {"schemaVersion": 1, "kind": "producer-readiness-preview",
            "units": window["units"], "media": media["admittedMedia"]}
    sha = digest(core)
    receipt = project / ".sniper-previews" / f"{sha}.json"
    value = {**core, "digest": sha}
    if receipt.exists():
        require(bound_json(receipt) == value, "Existing preview receipt changed")
    else:
        write_new(receipt, value)
    return {"key": media["key"], "window": window, "inspection": inspection,
            "receipt": str(receipt), "path": media["path"], "sha256": media["sha256"]}


def _windows(request: dict, prepared: tuple, root: Path, previous: dict | None) -> list[dict]:
    """Reuse exact clips; changed units obtain newly rendered full-context windows."""
    reference, preparation = prepared
    old = {row["key"]: row["inspection"] for row in (previous or {}).get("clips", [])}
    windows = preview_windows(request["plan"], request["packet"],
                              (preparation["frameRate"], preparation["totalFrames"]))
    clips = []
    for index, window in enumerate(windows):
        key = window_key(window, request, preparation)
        inspection = old.get(key)
        reused = inspection is not None
        if inspection is None:
            inspection = run_inspection(HERE, root / f"window-{index:04d}",
                {**request, "phase": "window", "preparation": reference, "window": window})
        clips.append({**_register(Path(request["project"]), window, inspection), "reused": reused})
    return clips


def generate(request: dict, root: Path, previous_file: Path | None) -> dict:
    """Produce an inspectable preview set; never export the finished full picture."""
    started = time.monotonic()
    _current(request)
    previous = prior_generation(previous_file, request["project"]) if previous_file else None
    root.mkdir(mode=0o700)
    preview_store = Path(request["project"]) / ".sniper-previews"
    preview_store.mkdir(mode=0o700, exist_ok=True)
    reference = run_inspection(HERE, root / "preparation", {**request, "phase": "prepare",
                               "previous": previous["preparation"] if previous else None})
    preparation = read_inspection(reference)
    clips = _windows(request, (reference, preparation), root, previous)
    _current(request)
    core = {"schemaVersion": 1, "kind": "ordinary-moving-previews", "status": "complete",
            "project": request["project"], "packet": request["packet"], "preparation": reference,
            "clips": clips, "baseReused": preparation["baseReused"], "masterReused": preparation["masterReused"],
            "elapsedSeconds": time.monotonic() - started, "editorialReview": "pending",
            "fullFinalCompositeRendered": False, "finalQcRequired": True,
            "coldCost": preparation["coldCost"], "conversationTokens": None}
    result = {**core, "digest": digest(core)}
    write_new(root / "ordinary-previews.json", result)
    return result


def main() -> None:
    """Expose one automatic command with explicit current-plan draft admission."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("producer", nargs="?", type=Path)
    parser.add_argument("manifest", nargs="?", type=Path)
    parser.add_argument("output", nargs="?", type=Path)
    parser.add_argument("--previous", type=Path)
    parser.add_argument("--worker", type=Path)
    args = parser.parse_args()
    if args.worker:
        worker(args.worker)
        return
    if not all((args.producer, args.manifest, args.output)):
        parser.error("producer directory, manifest and a new output directory are required")
    project, manifest = args.producer.resolve(strict=True), args.manifest.resolve(strict=True)
    plan = project / "edit_plan.json"
    request = {"project": str(project), "planPath": str(plan), "manifestPath": str(manifest),
               "plan": bound_json(plan), "manifest": bound_json(manifest)}
    request["packet"] = readiness_packet(_readiness(request))
    result = generate(request, args.output.absolute(), args.previous)
    print(json.dumps({key: value for key, value in result.items() if key not in {"clips", "packet"}}))


if __name__ == "__main__":
    main()
