"""TEST-only deadline adapter for the unchanged three-second source generator.

Generated bytes, admission fixture facts, and transcript binding are unchanged.
Only actual FFmpeg/probe timeout arguments are narrowed; no output is invented.
"""
from __future__ import annotations

import argparse
import sys
import time
from dataclasses import dataclass
from pathlib import Path

from palmier.process_deadline import use_process_deadline
import _cut_preview_fixture as fixture


@dataclass(frozen=True)
class LocalDeadline:
    """Local child cap; the original Node parent/group deadline stays authoritative."""

    expires_ns: int

    def remaining(self) -> float:
        """Reject elapsed original time; never manufacture a minimum credit."""
        value = (self.expires_ns - time.monotonic_ns()) / 1_000_000_000
        if not 0 < value <= 60:
            raise RuntimeError("TEST synthesis local deadline expired/invalid")
        return value


def run_fixture(root: Path, canvas: str, deadline: LocalDeadline) -> None:
    """Call the original fixture with real leaves and tighter timeouts only."""
    original_ffmpeg, original_argv = fixture.ffmpeg, sys.argv

    def bounded_ffmpeg(args: list[str], timeout: float = 20) -> None:
        """Forward actual native work under the same held expiry."""
        original_ffmpeg(args, min(timeout, deadline.remaining()))
        deadline.remaining()

    try:
        deadline.remaining()
        fixture.ffmpeg = bounded_ffmpeg
        sys.argv = [str(Path(fixture.__file__)), str(root), "--canvas", canvas]
        with use_process_deadline(deadline):
            fixture.main()
        deadline.remaining()
    finally:
        fixture.ffmpeg, sys.argv = original_ffmpeg, original_argv


def main() -> None:
    """Accept a bounded remainder without assuming cross-runtime clock epochs."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path)
    parser.add_argument("canvas", choices=("160x90", "1920x1080"))
    parser.add_argument("remaining_ms", type=int)
    args = parser.parse_args()
    if not 1 <= args.remaining_ms <= 60_000:
        raise RuntimeError("TEST synthesis handed remainder is invalid")
    deadline = LocalDeadline(time.monotonic_ns() + args.remaining_ms * 1_000_000)
    run_fixture(args.root, args.canvas, deadline)


if __name__ == "__main__":
    main()
