"""Real tiny local picture observations with explicit TEST-only admission metadata.

This fixture never invokes isolated admission, Docker, providers or a renderer.
Generated bytes and all actual tool output survive both success and failure.
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from unittest.mock import patch

import guided_presenter_observation as observation
from _guided_presenter_observation_fixture import held, selected_fixture
from guided_presenter_assets import SelectedPresenterAsset
from guided_presenter_observation import ObservedPresenterAsset, observe_presenter_asset
from guided_presenter_probe_identity import HeldPresenterProbeFile, PresenterObservationRuntime, PresenterProbePin
from headless.process_runner import ProcessRequest, run_text


@dataclass(frozen=True)
class PresenterObservationMediaCase:
    """Actual returned picture metadata; selected admission fields remain TEST-only."""
    selected: SelectedPresenterAsset
    source: HeldPresenterProbeFile
    observed: ObservedPresenterAsset


class OriginalMediaDeadline:
    """One original180s cohort clock, including setup, observation and consumer tests."""

    def __init__(self) -> None:
        """Begin before tool holds or generated source preparation."""
        self.started = time.monotonic()
        self.expires_at = self.started + 180

    def remaining(self) -> float:
        """Never renew the original fixture allowance."""
        remaining = self.expires_at - time.monotonic()
        if remaining <= 0:
            raise RuntimeError("TEST original presenter observation fixture clock expired")
        return remaining


class PresenterObservationMediaFixture:
    """Reusable real64×36 PNG and24-frame NTSC video, without duplicated probe work."""

    def __init__(self) -> None:
        """Retain one actual tool/runtime/source/probe scope and any failed attempt."""
        self.deadline = OriginalMediaDeadline()
        self.root = Path(tempfile.mkdtemp(prefix="sniper-presenter-observer-media-", dir="/private/tmp"))
        print(f"TEST-only selected picture observation fixture: {self.root}", flush=True)
        self.commands: list[dict] = []
        self.cases: dict[str, PresenterObservationMediaCase] = {}
        self.ffmpeg = self._tool("ffmpeg")
        self.runtime = PresenterObservationRuntime(self._tool("ffprobe"), str(self.root), self.deadline, lambda: None)
        try:
            self._case("still", True)
            self._case("video", False)
        except BaseException as error:
            self._record("failed", f"{type(error).__name__}: {error}")
            raise
        self._record("observed", None)

    def _tool(self, name: str) -> HeldPresenterProbeFile:
        """Hold actual installed tool bytes once; never install or resolve remotely."""
        self.deadline.remaining()
        found = shutil.which(name)
        if found is None:
            raise RuntimeError(f"TEST requires installed {name}")
        value = held(Path(found).resolve(strict=True))
        self.deadline.remaining()
        return value

    def _run(self, label: str, request: ProcessRequest) -> subprocess.CompletedProcess:
        """Capture unchanged actual owned runner return, including failed diagnostics."""
        started = time.monotonic()
        row = {"label": label, "argv": list(request.command)}
        self.commands.append(row)
        try:
            result = run_text(request)
        except BaseException as error:
            row.update(error=f"{type(error).__name__}: {error}", elapsedSeconds=time.monotonic() - started)
            raise
        (self.root / f"{label}.stdout").write_text(result.stdout)
        (self.root / f"{label}.stderr").write_text(result.stderr)
        row.update(returncode=result.returncode, elapsedSeconds=time.monotonic() - started,
                   remainingSeconds=self.deadline.remaining())
        return result

    def _generate(self, label: str, image: bool) -> Path:
        """Emit explicit native color/SAR metadata; actual probe must independently agree."""
        path = self.root / ("source.png" if image else "source.mp4")
        sound = ("-an",) if image else ("-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=1")
        common = (self.ffmpeg.path, "-hide_banner", "-loglevel", "error", "-nostdin", "-f", "lavfi",
            "-i", "color=c=gray:s=64x36:r=30000/1001:d=1", *sound, "-threads", "1")
        arguments = self._encoding(image)
        with PresenterProbePin(self.ffmpeg, self.runtime, True) as pin:
            request = ProcessRequest((*common, *arguments, str(path)), "", str(self.root),
                {"LANG": "C", "LC_ALL": "C"}, self.deadline.remaining(), max_output_bytes=1024 * 1024)
            result = self._run(f"{label}-generate", request)
            pin.assert_current()
        if result.returncode or result.stderr:
            raise RuntimeError("TEST actual source generation failed: " + result.stderr)
        return path

    def _encoding(self, image: bool) -> tuple[str, ...]:
        """Use actual tagged PNG and a video timescale that represents1001-tick frames."""
        if image:
            return ("-frames:v", "1", "-vf", "format=rgb24,setsar=1,"
                "setparams=colorspace=gbr:color_primaries=bt709:color_trc=iec61966-2-1:range=full",
                "-c:v", "png", "-pix_fmt", "rgb24", "-update", "1")
        return ("-frames:v", "24", "-vf", "setsar=1,"
            "setparams=colorspace=bt709:color_primaries=bt709:color_trc=bt709:range=limited",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-colorspace", "bt709",
            "-color_primaries", "bt709", "-color_trc", "bt709", "-color_range", "tv",
            "-video_track_timescale", "30000", "-c:a", "aac", "-b:a", "64000", "-shortest")

    def _case(self, label: str, image: bool) -> None:
        """Call the production observer with real outputs and explicit TEST admission rows."""
        path = self._generate(label, image)
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        store = self.root / ".sniper-external-media"
        store.mkdir(exist_ok=True)
        target = store / f"{digest}.media"
        path.rename(target)
        source = held(target)
        selected = selected_fixture(source, image, f"TEST-{label}")
        count = 0

        def capture(request: ProcessRequest) -> subprocess.CompletedProcess:
            """Only record the real owned runner; never substitute probe stdout."""
            nonlocal count
            count += 1
            return self._run(f"{label}-probe-{count}", request)

        with patch.object(observation, "run_text", capture):
            observed = observe_presenter_asset(selected, source, "30000/1001", self.runtime)
        self.cases[label] = PresenterObservationMediaCase(selected, source, observed)

    def _record(self, status: str, error: str | None) -> None:
        """Keep exact scope and elapsed costs, including failed actual attempts."""
        report = {"scope": "actual-tiny-picture-observation-with-TEST-only-admission-metadata",
            "status": status, "error": error, "commands": self.commands,
            "elapsedSeconds": time.monotonic() - self.deadline.started,
            "isolatedAdmissionVerified": False, "rightsVerified": False, "renderApproved": False}
        (self.root / "TEST-observations.json").write_text(json.dumps(report, indent=2) + "\n")
