"""Actual source holders and encode hooks around explicitly inert TEST output files.

The synthetic OpeningPreparation does NOT qualify a source, selection, frame,
audio packet, video or creator review. It only composes real retained control
flow and output-byte publication, with all existing native/proof leaves stubbed.
"""
from __future__ import annotations

from contextlib import ExitStack
from pathlib import Path
import stat
from types import SimpleNamespace

from _source_color_consumption_fixture import SourceColorConsumptionFixture
from _source_color_consumption_render_fixture import SourceColorRenderFixture
from compile_timeline import compile_plan
from cross_runtime_canonical_json import canonical_compact_json
from cut_manifestation_authority import MANIFESTATION_NAME, _receipt_hash
from cut_preview_io import file_hash, write_new
from guided_opening_prepare import OpeningPreparation
import render


class SourceColorMediaEvidenceFixture:
    """Own every inert output and restrict intentional faults to its named TEST files."""

    def __init__(self, pins: list[dict]) -> None:
        """Create actual retained source metadata; never run FFmpeg or a media admission."""
        self.source = SourceColorConsumptionFixture(pins)
        self.context = self.source.base_context(self.source.identity())
        self.root = Path(self.source.opening.value["outputRoot"])
        self.base = self.root / "full-program-base"
        self.base.mkdir(parents=True, mode=0o700)
        self.timeline = self.base / "timeline_map.json"
        write_new(self.timeline, compile_plan(self.source.inputs.documents["candidatePlan"]).to_dict())
        self.base_path = self.base / "final.mp4"
        self.base_path.write_bytes(b"TEST inert generated bytes: not an MP4 or a media-quality proof")
        self.base_sha = file_hash(self.base_path)
        self.live = SourceColorRenderFixture(self.source, self.context)
        self.live.ctx.out_dir, self.live.ctx.work_dir = str(self.base), str(self.base / "work")
        self.original_manifestation = self.source.manifestation
        self.source.manifestation = self.manifestation
        self.live.seal = self.seal
        self.allowed = {self.base_path, self.timeline, self.base / MANIFESTATION_NAME,
                        self.base / "master-receipt.json", self.root / "source-color-evidence.json"}

    def cleanup(self) -> None:
        """Remove only the owning standard TemporaryDirectory tree from the inherited fixture."""
        self.source.cleanup()

    def manifestation(self, inputs: object) -> dict:
        """Retain real closed manifestation semantics with explicitly synthetic frame/probe leaves."""
        record = self.original_manifestation(inputs)
        record["timelineMapSha256"] = file_hash(self.timeline)
        record["receiptHash"] = _receipt_hash(record)
        write_new(self.base / MANIFESTATION_NAME, record)
        return record

    def seal(self, path: str, body: dict) -> dict:
        """Match actual publisher byte spelling in an owned TEST artifact, not real media evidence."""
        record = {**body, "receiptHash": _receipt_hash(body)}
        if Path(path) != self.base / "master-receipt.json":
            raise AssertionError("TEST publisher escaped exact owned master role")
        with Path(path).open("xb") as stream:
            stream.write(canonical_compact_json(record).encode("utf-8"))
        self.live.sealed = record
        return record

    def ready(self) -> OpeningPreparation:
        """Complete actual lower hooks, then label selection/full output proof as TEST-only."""
        with ExitStack() as stack:
            self.live.cut_leaves(stack)
            source = render.cut_stage(self.live.ctx)
            leaves = self.live.master_leaves(stack)
            leaves["file_sha256"].return_value = self.base_sha
            render.master_stage(self.live.ctx, source, None)
        evidence = {"base": {"path": str(self.base_path), "sha256": self.base_sha,
                               "sizeBytes": self.base_path.stat().st_size},
                    "receipts": {name: {"path": str(path), "sha256": file_hash(path)} for name, path in (
                        ("cutManifestation", self.base / MANIFESTATION_NAME), ("timelineMap", self.timeline))}}
        return OpeningPreparation(self.base_path, SimpleNamespace(TEST="selection not qualified"), evidence)

    def change(self, path: Path, data: bytes) -> None:
        """Intentional faults may touch only exact existing single-link canonical TEST outputs."""
        info = path.lstat()
        if path not in self.allowed or path.resolve(strict=True) != path or not path.is_relative_to(self.root) \
                or not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
            raise AssertionError("TEST mutation is not an exact owned output")
        path.write_bytes(data)
