"""Actual batch metadata/holds, with TEST admission and socket-type leaves only.

Sources are inert generated bytes. Opening document refs are explicitly not
14-document admission. Required implementation hashes are real current code;
no decoder, daemon, resource lease, worker or project approval is exercised.
"""
from __future__ import annotations

import json
import os
import stat
import time
from contextlib import ExitStack
from dataclasses import replace
from pathlib import Path
from unittest.mock import Mock, patch
from uuid import uuid4

from _grade_launch_fixture import GradeLaunchFixture
from _source_color_preparation_fixture import SourceColorPreparationFixture
from color import grade_project
from color import grade_project_input
from cut_preview_io import digest, file_hash, write_new
from guided_opening_inputs import DOCUMENTS
from guided_source_color_batch import SourceColorJobRef, prepare_source_color_batch
from guided_source_color_hold import hold_source_color_preparation
from headless.durable_files import write_all
from headless.grade_launch_intent import OwnedGradeLaunch


def current_batch_test_pins() -> list[dict]:
    """Capture actual required code once per TEST cohort, never a production cache."""
    rows = {row["path"]: row["sha256"] for row in grade_project.implementation()}
    reader = Path(grade_project_input.__file__).resolve()
    for path in (reader, reader.with_name("grade_project_worker.py")):
        rows[str(path)] = file_hash(path)
    return [{"path": path, "sha256": sha} for path, sha in sorted(rows.items())]


class SourceColorBatchFixture(SourceColorPreparationFixture):
    """Reuse real original capture and parser helpers on one exact TEST tree."""

    def __init__(self, pins: list[dict]) -> None:
        """Author complete TEST job/preclaim metadata before taking the original hold."""
        super().__init__()
        self.stack = ExitStack()
        self.now = 1000.0
        self.stack.enter_context(patch.object(time, "monotonic", side_effect=lambda: self.now))
        self.stack.enter_context(patch("headless.grade_launch_intent.verify_runtime_controls", side_effect=self._runtime_check))
        self.runtime_controls = GradeLaunchFixture._runtime(self)
        self.extra_code = self.root / "TEST-extra-code.py"
        write_new(self.extra_code, {"testOnly": "inert declared extra pin"})
        self.pins = [*pins, {"path": str(self.extra_code), "sha256": file_hash(self.extra_code)}]
        self.opening_claim = self._opening()
        self.input_values, self.claim_values, self.input_paths, self.claim_paths = {}, {}, {}, {}
        self.allowed_faults = {self.extra_code, self.inputs.path, self.opening_claim}
        self.held = hold_source_color_preparation(self.inputs, self.declarations, self.context)
        self.refs = tuple(self._job(row) for row in self.held.jobs)

    def _runtime_check(self, runtime: dict, snapshot: str) -> None:
        """Retain actual control checks; only the inert socket sentinel type is stubbed."""
        GradeLaunchFixture._verify_runtime(self, runtime, snapshot)

    def _opening(self) -> Path:
        """Create original opening identity refs without claiming admitted documents."""
        directory = self.root / "opening"
        directory.mkdir(mode=0o700)
        refs = dict(self.inputs.value["documents"])
        for name in sorted(DOCUMENTS - set(refs)):
            path = directory / f"{name}.json"
            write_new(path, {"TEST": name, "admissionVerified": False})
            refs[name] = {"path": str(path), "sha256": file_hash(path)}
        value = {"schemaVersion": 1, "kind": "guided-opening-media-input", "executionId": str(uuid4()),
            "profile": "unity-source-float-own-screen-v1", "documents": refs,
            "pipeline": {"snapshotRoot": str(self.snapshot), "lockPath": str(self.root / "TEST-lock.json"),
                         "lockSha256": "e" * 64, "digest": "f" * 64}}
        value["executionInputHash"] = digest(value)
        path = directory / "input.json"
        write_new(path, value)
        self.inputs = replace(self.inputs, path=path, sha256=file_hash(path), value=value)
        claim = directory / "execution-claim.json"
        write_new(claim, {"schemaVersion": 1, "kind": "guided-opening-execution-claim",
            "scope": "private-opening-owned-execution-not-approval", "requestId": str(uuid4()),
            "executionId": value["executionId"], "beforeJournalHash": "b" * 64, "inputPath": str(path),
            "inputSha256": self.inputs.sha256, "executionInputHash": value["executionInputHash"],
            "outputRoot": str(directory), "clockHash": "c" * 64, "generationStartedAt": "2026-09-08T00:00:00.000Z",
            "budgetAdmissionHash": "d" * 64, "selectedGraphicOrders": [], "runtime": self.runtime_controls})
        return claim

    def _job(self, prepared: object) -> SourceColorJobRef:
        """Create only TEST input/preclaim files; leave prospective execution absent."""
        metadata = prepared.record()
        source_id, job_id = prepared.binding.source_id, str(uuid4())
        directory = self.producer / ".sniper-grade-observations" / job_id
        directory.mkdir(parents=True, mode=0o700)
        inventory = directory / "implementation.json"
        write_new(inventory, {"files": self.pins})
        value = {key: metadata[key] for key in ("schemaVersion", "policy", "sourceId", "declaration", "expected")}
        value.update(jobId=job_id, producerDir=str(self.producer), ownerPid=os.getppid(),
                     implementationSha256=file_hash(inventory))
        if "profile" in metadata:
            value["profile"] = metadata["profile"]
        path = directory / "input.json"
        write_new(path, value)
        claim = {"schemaVersion": 1, "kind": "owned-grade-launch-claim",
            "scope": "preclaimed-source-observation-not-recovery-or-approval", "jobId": job_id,
            "inputPath": str(path), "inputSha256": file_hash(path), "executionDir": str(directory / "execution"),
            "sourcePath": prepared.source.path, "sourceSha256": prepared.source.sha256,
            "frameCount": prepared.binding.frame_count, "profile": prepared.profile.token,
            "containerName": "sniper-grade-observation-" + job_id.replace("-", ""),
            "openingClaimPath": str(self.opening_claim), "openingClaimSha256": file_hash(self.opening_claim),
            "runtime": self.runtime_controls}
        claim_path = directory / "launch-claim.json"
        write_new(claim_path, claim)
        self.input_values[source_id], self.claim_values[source_id] = value, claim
        self.input_paths[source_id], self.claim_paths[source_id] = path, claim_path
        self.allowed_faults.update((path, inventory, claim_path))
        launch = OwnedGradeLaunch(claim_path, file_hash(claim_path), self.context.deadline, Mock())
        return SourceColorJobRef(source_id, path, file_hash(path), launch)

    def change(self, path: Path, value: object) -> None:
        """Mutate only explicitly named canonical TEST regular single-link files."""
        if path not in self.allowed_faults or not path.is_relative_to(self.root) or path.resolve(strict=True) != path:
            raise RuntimeError("source color batch fault target is not explicitly TEST-owned")
        before = path.lstat()
        if not stat.S_ISREG(before.st_mode) or before.st_nlink != 1 or before.st_uid != os.geteuid():
            raise RuntimeError("source color batch fault target is not a regular single-link TEST file")
        descriptor = os.open(path, os.O_WRONLY | os.O_NOFOLLOW)
        try:
            current = os.fstat(descriptor)
            if (current.st_dev, current.st_ino) != (before.st_dev, before.st_ino):
                raise RuntimeError("source color batch TEST target changed before write")
            raw = value if type(value) is bytes else json.dumps(value).encode()
            os.ftruncate(descriptor, 0)
            write_all(descriptor, raw)
        finally:
            os.close(descriptor)

    def rewrite_job(self, index: int, changes: dict) -> None:
        """Author changed TEST metadata before preflight, retaining exact new raw hashes."""
        ref = self.refs[index]
        value = {**self.input_values[ref.source_id], **changes}
        self.change(ref.input_path, value)
        claim = {**self.claim_values[ref.source_id], "inputSha256": file_hash(ref.input_path)}
        self.change(ref.launch.claim_path, claim)
        changed = replace(ref, input_sha256=file_hash(ref.input_path), launch=OwnedGradeLaunch(
            ref.launch.claim_path, file_hash(ref.launch.claim_path), ref.launch.deadline, ref.launch.guard))
        rows = list(self.refs)
        rows[index] = changed
        self.refs = tuple(rows)

    def prepare(self) -> object:
        """Run the real complete batch metadata path, never a worker."""
        return prepare_source_color_batch(self.held, self.refs)

    def rewrite_claim(self, index: int, changes: dict) -> None:
        """Change only an explicitly named TEST preclaim before capturing its new SHA."""
        ref = self.refs[index]
        claim = {**self.claim_values[ref.source_id], **changes}
        self.change(ref.launch.claim_path, claim)
        launch = OwnedGradeLaunch(ref.launch.claim_path, file_hash(ref.launch.claim_path),
                                  ref.launch.deadline, ref.launch.guard)
        rows = list(self.refs)
        rows[index] = replace(ref, launch=launch)
        self.refs = tuple(rows)

    def cleanup(self) -> None:
        """Close patches and remove only this exact inherited TEST root."""
        self.stack.close()
        super().cleanup()
