"""Regression pin for the native caption grouper without protected phrases (P2-05, M-070).

``native_caption_groups_golden.json`` holds grouper inputs and what the pre-M-070 ``native_groups`` returned
(or raised) for each. The outputs were generated by running that function, never written by hand; the file's
``provenance`` names the generator, its sha256 and the base blobs. M-070 adds protected phrases: with none
declared (absent or ``[]``), every outcome must stay identical, or M-070 stops (P2-05 Stop). That includes the
refusal text for empty and malformed input, since M-070 edits ``_words``, which validates it.
"""
from __future__ import annotations

import _live_state_isolation  # noqa: F401  private budget/pool roots; live state refused

import json
import unittest
from pathlib import Path

from studio import native_caption_groups as grouper

GOLDEN = Path(__file__).resolve().parent / 'native_caption_groups_golden.json'
REQUIRED = frozenset({'several-speakers', 'gaps', 'punctuation', 'long-words', 'phrase-boundary', 'empty-input',
                      'source-cut', 'word-cap', 'sentence-end', 'float-edge', 'malformed-input'})
REFUSALS = 13  # 2 empty inputs + 11 malformed ones


def cases() -> list[dict]:
    """The golden cases, in file order."""
    return json.loads(GOLDEN.read_text(encoding='utf-8'))['cases']


def outcome(value: object) -> dict:
    """The grouper's result for one input, in the golden file's form."""
    try:
        return {'groups': grouper.native_groups(value)}
    except ValueError as error:
        return {'error': {'type': type(error).__name__, 'message': str(error)}}


class NoPhraseGroupingPinTests(unittest.TestCase):
    """Grouping without protected phrases equals the recorded pre-M-070 outcome, case by case."""

    def test_no_phrases_matches_previous_grouping(self) -> None:
        """Each golden input groups, or is refused, exactly as the pre-change function did."""
        for case in cases():
            expected = {key: case[key] for key in ('groups', 'error') if key in case}
            with self.subTest(case=case['name']):
                self.assertEqual(outcome(case['input']), expected)

    def test_golden_catalog_keeps_every_case_kind(self) -> None:
        """The pin cannot be thinned: required kinds present, names unique, no phrase declared, every refusal kept."""
        rows = cases()
        self.assertLessEqual(REQUIRED, {tag for row in rows for tag in row['covers']})
        self.assertEqual(len({row['name'] for row in rows}), len(rows))
        declared = [row['name'] for row in rows
                    if isinstance(row['input'], dict) and row['input'].get('protectedPhrases')]
        self.assertEqual(declared, [])
        self.assertEqual(sum('error' in row for row in rows), REFUSALS)


if __name__ == '__main__':
    unittest.main()
