"""Validate synthetic UI fixtures against real gates, never _common's matrix."""
from __future__ import annotations

import hashlib
import html
import json
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[3]
_FACTORY = Path(__file__).parent / "fixtures" / "create_studio_ui_fixture.py"


def _run(args: list[str]) -> dict:
    """Isolate production imports from the broader suite's synthetic matrix."""
    result = subprocess.run([sys.executable, *args], capture_output=True,
                            text=True, check=True, timeout=60)
    return json.loads(result.stdout)


def _replace_slot(source: str, slot: str, edit: str) -> str:
    """Simulate only native HTML attribute serialization, not source code edits."""
    pattern = rf'<div\b[^>]*\bid="{slot}"[^>]*>'
    matches = list(re.finditer(pattern, source))
    if len(matches) != 1:
        raise AssertionError("expected one generated host slot")
    original = matches[0].group()
    if edit == "timing":
        changed, count = re.subn(r'data-duration="2\.5"',
                                 'data-duration="3.5"', original)
        if count != 1:
            raise AssertionError("expected original 2.5-second clip")
    else:
        match = re.search(r"data-variable-values='([^']*)'", original)
        if match is None:
            raise AssertionError("expected generated variable values")
        values = json.loads(html.unescape(match.group(1)))
        values["label"] = edit
        attribute = 'data-variable-values="' + html.escape(json.dumps(values)) + '"'
        changed = original.replace(match.group(), attribute)
    return source.replace(original, changed, 1)


def _capture(studio: Path, manifest: dict, host: str) -> dict:
    """Capture exact generated bytes with an in-memory supported host edit."""
    files, texts = {}, {}
    for relative in [*manifest["files"], "studio.manifest.json"]:
        raw = host.encode() if relative == "index.html" else (studio / relative).read_bytes()
        files[relative] = hashlib.sha256(raw).hexdigest()
        if relative.endswith(".html"):
            texts[relative] = raw.decode("utf8")
    return {"files": files, "textFiles": texts}


def _validate_workflow(producer: Path) -> dict:
    """Run real generator and strict import bridge without saving any draft."""
    sys.path.insert(0, str(_FACTORY.parent))
    sys.path.insert(0, str(_ROOT / "src/app/api/producer/studio/import"))
    from create_studio_ui_fixture import validate_fixture_plan
    from studio.studio_project import GenerateRequest, generate_project
    from bridge import baseline, diff
    plan = json.loads((producer / "edit_plan.json").read_text())
    assets = json.loads((producer / "asset_manifest.json").read_text())
    studio = producer / "studio"
    generate_project(GenerateRequest(str(producer / "edit_plan.json"),
                                     str(producer / "base_final.mp4"), str(studio)))
    originals = baseline({"dir": str(producer)})
    manifest_text = (studio / "studio.manifest.json").read_text()
    session = {"originalPlan": plan, "manifestText": manifest_text, **originals}
    host = originals["host"]
    timed = _replace_slot(host, "gfx-01", "timing")
    copied = _replace_slot(timed, "gfx-03", "Checked")
    repeated = _replace_slot(timed, "gfx-03", "Ready")
    outcomes = {}
    for name, candidate_host in (("original", host), ("timing", timed),
                                 ("copy", copied), ("repeated", repeated), ("undo", host)):
        capture = _capture(studio, json.loads(manifest_text), candidate_host)
        result = diff({"dir": str(producer), "session": session, "capture": capture})
        if result["blockers"] or result["warnings"]:
            raise AssertionError(result)
        validate_fixture_plan(result["candidate"], assets, producer)
        track = result["candidate"]["graphicsTrack"]
        outcomes[name] = {"end": track[0]["outEnd"], "label": track[2]["spec"]["label"]}
        if result["candidate"]["cutTrack"] != plan["cutTrack"]:
            raise AssertionError("graphics edit changed cuts")
    if json.loads((producer / "edit_plan.json").read_text()) != plan:
        raise AssertionError("read-only bridge modified draft")
    return outcomes


def _mean_luma(video: Path, seconds: float) -> int:
    """Measure the hook band only; this is structural media proof, not QC."""
    result = subprocess.run([
        "ffmpeg", "-nostdin", "-v", "error", "-ss", str(seconds), "-i", str(video),
        "-frames:v", "1", "-vf", "crop=1080:600:0:0,scale=1:1,format=gray",
        "-f", "rawvideo", "-", ], capture_output=True, check=True, timeout=10)
    if len(result.stdout) != 1:
        raise AssertionError("expected one luminance sample")
    return result.stdout[0]


class StudioUiFixtureTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.temporary = tempfile.TemporaryDirectory(prefix="studio-fixture-test-")
        cls.workspace = Path(cls.temporary.name)
        cls.result = _run([str(_FACTORY), str(cls.workspace)])
        cls.producer = Path(cls.result["producerDir"])

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temporary.cleanup()

    def test_real_plan_validity_and_truthful_non_dialogue_metadata(self) -> None:
        self.assertEqual(self.result["planErrors"], [])
        plan = json.loads((self.producer / "edit_plan.json").read_text())
        self.assertEqual(plan["target"]["mode"], "short")
        self.assertEqual(plan["target"]["scope"], "light")
        self.assertNotIn("excerpt", plan["target"])
        manifest = json.loads((self.producer / "asset_manifest.json").read_text())
        source = manifest["sources"][0]
        transcript = json.loads(Path(source["transcriptPath"]).read_text())
        self.assertEqual(transcript["words"], [])
        self.assertEqual(source["resolution"], [1080, 1920])
        self.assertEqual(source["contentHash"], hashlib.sha256(Path(source["path"]).read_bytes()).hexdigest())
        self.assertFalse((self.producer / "final.mp4").exists())
        self.assertFalse((self.producer / "critic.json").exists())
        self.assertFalse((self.producer / "delivery-receipt.json").exists())

    def test_declared_hook_is_really_in_base_and_exits(self) -> None:
        source = self.producer.parent / "source/raw-1.mp4"
        base = self.producer / "base_final.mp4"
        self.assertGreater(_mean_luma(base, 0) - _mean_luma(source, 0), 20)
        self.assertLessEqual(abs(_mean_luma(base, 2) - _mean_luma(source, 2)), 1)

    def test_timing_copy_repeat_and_undo_pass_strict_import_and_real_gates(self) -> None:
        outcomes = _run([__file__, "--validate", str(self.producer)])
        self.assertEqual(outcomes["original"], {"end": 3.5, "label": "Review"})
        self.assertEqual(outcomes["timing"], {"end": 4.5, "label": "Review"})
        self.assertEqual(outcomes["copy"], {"end": 4.5, "label": "Checked"})
        self.assertEqual(outcomes["repeated"], {"end": 4.5, "label": "Ready"})
        self.assertEqual(outcomes["undo"], outcomes["original"])

    def test_existing_project_and_registry_are_not_overwritten(self) -> None:
        registry = self.workspace / ".project-sniper/projects.json"
        original = registry.read_bytes()
        with self.assertRaises(subprocess.CalledProcessError):
            _run([str(_FACTORY), str(self.workspace)])
        with self.assertRaises(subprocess.CalledProcessError):
            _run([str(_FACTORY), str(self.workspace), "../escape"])
        self.assertEqual(registry.read_bytes(), original)

    def test_changed_base_or_source_cannot_enter_studio_import(self) -> None:
        """The real bridge rejects byte changes even with an unchanged plan."""
        targets = [self.producer / "base_final.mp4",
                   self.producer.parent / "source/raw-1.mp4"]
        for target in targets:
            with self.subTest(target=target.name):
                original = target.read_bytes()
                try:
                    target.write_bytes(original + b"changed synthetic test bytes")
                    with self.assertRaises(subprocess.CalledProcessError) as raised:
                        _run([__file__, "--validate", str(self.producer)])
                    self.assertIn("base is stale", raised.exception.stderr)
                finally:
                    target.write_bytes(original)


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "--validate":
        print(json.dumps(_validate_workflow(Path(sys.argv[2]))))
    else:
        unittest.main()
