#!/usr/bin/env python3
"""Run the shipped Python test suite inside an installed package and gate it.

    python3 -m release.package_selftest <installed-package-root> --withheld <withheld.json> --out <result.json>

The package ships the Producer engine's tests but withholds the maintainer's
retained qualification evidence and the container build inputs. A test that
verifies withheld evidence cannot pass inside the package. It is tolerated only
when BOTH hold:

1. the test is declared below with the reason its input is not a product input
   (runtime reachability recorded per entry), and
2. its TERMINAL exception, recorded structurally by the runner (type, errno,
   filename; never parsed from traceback text, never an earlier exception in a
   chain), is exactly FileNotFoundError/ENOENT for a path that is absent from the
   package and that this build's withheld manifest lists (a withheld file, or a
   file under a withheld folder).

Every other failure or error fails the gate, including a failed or errored
subtest and an unexpected success. The recorded rows must agree with unittest's
own totals. Declared tests that pass are reported. Nothing is skipped: every test
runs.

A result is accepted only from the run the gate just started: the runner writes
to a fresh private file, echoes a per-run nonce and must exit 0. Any previous
``--out`` is removed before the run, and an infrastructure failure (the runner
crashed, wrote nothing, wrote a truncated or foreign file) writes a failing
result, never an earlier pass.
"""
from __future__ import annotations

import argparse
import errno
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

# test-id prefix → why its input is not read by any buyer workflow
DEV_EVIDENCE: dict[str, str] = {
    "test_comp_rate_matrix.": "retained HyperFrames rate matrix; read only by the maintainer's comp_rate_oci tooling",
    "test_current_system_inventory_check.": "retained system inventory; read only by the maintainer checker "
                                            "current_system_inventory_check.py",
    "test_graphics_runtime_closure.GraphicsRuntimeClosureTests.test_image_build_includes_all_observer_modules":
        "container image build inputs (templates/motion/.dockerignore); the Mac package has no container route",
    "test_p0_adversarial_ingress_artifact.": "retained hostile-ingress evidence (regenerated by the maintainer's "
                                             "live_p0_adversarial_ingress_acceptance.py)",
    "test_p0_render_effect_parity_artifact.": "retained render-parity evidence root (local, ~21 GB)",
    "test_p2_row1_claim_artifact.": "retained P2 claim cohort evidence",
    "test_p2_visual_lip_sync_artifact.": "retained lip-sync evidence under scripts/producer/artifacts",
    "test_p4_exit_closure_artifact.": "retained P4 live exit-closure evidence",
    "test_p5_compositor_artifact.": "retained P5 compositor evidence",
    "test_p5_review_repair_artifact.": "retained P5 review-repair evidence",
    "test_render_layout_transport.": "container layout observer (templates/motion/container); reachable only through "
                                     "the container-only guided opening/body path, which refuses on the Mac package",
    "test_scene_brief_matrix.": "retained P4 scene-brief matrix evidence",
}
# unittest reports class/module fixture errors under a holder id, e.g. "setUpClass (mod.Class)".
_FIXTURE_ID = re.compile(r"^(?:setUpClass|tearDownClass|setUpModule|tearDownModule) \((.+)\)$")

_RUNNER = r"""
import json, os, sys, traceback, unittest
tests = os.path.join(os.getcwd(), "tests"); sys.path.insert(0, tests); sys.path.insert(0, os.getcwd())
out, nonce = sys.argv[1], sys.argv[2]
class Result(unittest.TextTestResult):
    rows = []
    def _row(self, test, outcome, err=None, subtest=None):
        text = "".join(traceback.format_exception(*err)) if err else ""
        row = {"id": test.id(), "outcome": outcome, "detail": text[-4000:]}
        if err is not None:  # the TERMINAL exception only, recorded as data
            exc = err[1]
            name = getattr(exc, "filename", None)
            row["exc"] = {"type": type(exc).__module__ + "." + type(exc).__qualname__,
                          "errno": getattr(exc, "errno", None), "filename": name if isinstance(name, str) else None}
        if subtest is not None:
            row["subtest"] = subtest.id()
        Result.rows.append(row)
    def addSuccess(self, test): super().addSuccess(test); self._row(test, "pass")
    def addFailure(self, test, err): super().addFailure(test, err); self._row(test, "fail", err)
    def addError(self, test, err): super().addError(test, err); self._row(test, "error", err)
    def addSkip(self, test, reason): super().addSkip(test, reason); Result.rows.append({"id": test.id(), "outcome": "skip", "detail": reason})
    def addExpectedFailure(self, test, err): super().addExpectedFailure(test, err); self._row(test, "xfail", err)
    def addUnexpectedSuccess(self, test):
        super().addUnexpectedSuccess(test); Result.rows.append({"id": test.id(), "outcome": "fail", "detail": "unexpected success"})
    def addSubTest(self, test, subtest, err):
        super().addSubTest(test, subtest, err)
        if err is not None:
            self._row(test, "fail" if issubclass(err[0], test.failureException) else "error", err, subtest)
suite = unittest.TestLoader().discover(start_dir=tests, top_level_dir=tests, pattern="test_*.py")
result = unittest.TextTestRunner(verbosity=1, resultclass=Result, stream=sys.stderr).run(suite)
summary = {"testsRun": result.testsRun, "failures": len(result.failures), "errors": len(result.errors),
           "unexpectedSuccesses": len(result.unexpectedSuccesses), "wasSuccessful": result.wasSuccessful()}
with open(out + ".partial", "w") as handle:
    json.dump({"nonce": nonce, "complete": True, "summary": summary, "rows": Result.rows}, handle)
os.replace(out + ".partial", out)
"""


class GateInfrastructureError(RuntimeError):
    """The test run did not produce a trustworthy result."""


@dataclass(frozen=True)
class Withheld:
    """This build's withheld manifest: exact files and whole folders (package-relative)."""

    files: frozenset[str]
    folders: tuple[str, ...]

    @classmethod
    def load(cls, path: Path) -> "Withheld":
        rows = json.loads(path.read_text(encoding="utf-8"))
        return cls(frozenset(row["path"] for row in rows if row.get("kind") != "folder"),
                   tuple(row["path"].rstrip("/") for row in rows if row.get("kind") == "folder"))

    def lists(self, relative: str) -> bool:
        return relative in self.files or any(relative.startswith(folder + "/") for folder in self.folders)


def _declared(test_id: str) -> str | None:
    """The reason a test's input is development-only, if declared (fixture holders map to their class)."""
    fixture = _FIXTURE_ID.match(test_id)
    name = fixture.group(1) + "." if fixture else test_id
    return next((reason for prefix, reason in DEV_EVIDENCE.items() if name.startswith(prefix)), None)


def _withheld_miss(row: dict, package_app: Path, withheld: Withheld) -> bool:
    """Whether the row's terminal exception is a missing withheld file absent from the package."""
    exc = row.get("exc") or {}
    if exc.get("type") != "builtins.FileNotFoundError" or exc.get("errno") != errno.ENOENT:
        return False
    if not isinstance(exc.get("filename"), str) or not exc["filename"]:
        return False
    path = Path(exc["filename"])
    path = path if path.is_absolute() else package_app / "scripts" / "producer" / path
    try:
        relative = path.resolve(strict=False).relative_to(package_app.resolve()).as_posix()
    except ValueError:
        return False
    return not (package_app / relative).exists() and withheld.lists(relative)


def _reconcile(rows: list[dict], summary: dict) -> list[dict]:
    """Gate failures when the recorded rows disagree with unittest's own totals."""
    failing = sum(row["outcome"] in ("fail", "error") for row in rows)
    expected = summary["failures"] + summary["errors"] + summary["unexpectedSuccesses"]
    if failing == expected and summary["wasSuccessful"] == (failing == 0):
        return []
    return [{"id": "<unittest totals>", "outcome": "error",
             "detail": f"recorded {failing} failing outcomes; unittest reported {expected} "
                       f"(wasSuccessful={summary['wasSuccessful']})"}]


def classify(rows: list[dict], package_app: Path, withheld: Withheld, summary: dict | None = None) -> dict:
    """Split results into passes, tolerated withheld-evidence failures and gate failures."""
    tolerated, failures = [], []
    for row in rows:
        if row["outcome"] not in ("fail", "error"):
            continue
        reason = _declared(row["id"])
        entry = {"id": row["id"], **({"subtest": row["subtest"]} if "subtest" in row else {})}
        if reason and _withheld_miss(row, package_app, withheld):
            tolerated.append({**entry, "reason": reason})
        else:
            failures.append({**entry, "outcome": row["outcome"], "detail": row["detail"][-1200:]})
    if summary is not None:
        failures.extend(_reconcile(rows, summary))
    counts = {key: sum(row["outcome"] == key for row in rows) for key in ("pass", "fail", "error", "skip", "xfail")}
    # Skips come from each test's own condition (a tool or opt-in it needs); listed so a reviewer
    # can see what did not run inside the package, not only how many.
    skipped = [{"id": row["id"], "reason": row["detail"]} for row in rows if row["outcome"] == "skip"]
    return {"counts": counts, "total": len(rows), "toleratedWithheldEvidence": tolerated,
            "skipped": skipped, "gateFailures": failures, "passed": not failures and counts["pass"] > 0}


def _load_run(path: Path, nonce: str, returncode: int) -> tuple[list[dict], dict]:
    """The rows of the run just started, or GateInfrastructureError."""
    if returncode != 0:
        raise GateInfrastructureError(f"the test runner exited {returncode}")
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise GateInfrastructureError(f"the test runner wrote no readable result ({error})") from error
    if type(document) is not dict or document.get("nonce") != nonce or document.get("complete") is not True:
        raise GateInfrastructureError("the result file is not this run's complete result")
    rows, summary = document.get("rows"), document.get("summary")
    if type(rows) is not list or type(summary) is not dict:
        raise GateInfrastructureError("the result file is malformed")
    return rows, summary


def _run_suite(app: Path) -> tuple[list[dict], dict]:
    """Run the shipped suite in a fresh private folder; return its rows and unittest totals."""
    python = app / ".venv" / "bin" / "python3"
    work = Path(tempfile.mkdtemp(prefix="sniper-package-selftest-"))
    try:
        rows_path, nonce = work / "rows.json", secrets.token_hex(16)
        # The documented command (AGENTS.md "Checks"): cd scripts/producer && PYTHONPATH=.:tests …
        # Tests that start the engine's own CLIs rely on that PYTHONPATH, as the product's
        # launchers set it for the CLIs they start (e.g. cut-repair-route-runner.ts).
        producer = app / "scripts" / "producer"
        done = subprocess.run([str(python), "-B", "-c", _RUNNER, str(rows_path), nonce], cwd=producer,
                              env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1",
                                   "PYTHONPATH": f"{producer}:{producer / 'tests'}"}, check=False)
        return _load_run(rows_path, nonce, done.returncode)
    finally:
        shutil.rmtree(work, ignore_errors=True)


def _write(out: Path, result: dict) -> None:
    out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("package", type=Path, help="installed package root (the app folder, with its .venv)")
    parser.add_argument("--withheld", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    args.out.unlink(missing_ok=True)  # an earlier pass must never stand for this run
    app = args.package   # the package folder is the app folder
    try:
        rows, summary = _run_suite(app)
    except GateInfrastructureError as error:
        _write(args.out, {"passed": False, "infrastructureError": str(error)})
        print(f"GATE INFRASTRUCTURE FAILURE: {error}", file=sys.stderr)
        return 2
    result = classify(rows, app, Withheld.load(args.withheld), summary)
    _write(args.out, result)
    print(json.dumps({key: result[key] for key in ("counts", "total", "passed")}))
    for row in result["gateFailures"]:
        print(f"GATE FAILURE {row['outcome']}: {row['id']}", file=sys.stderr)
    return 0 if result["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
