#!/usr/bin/env python3
"""Run the shipped Python test suite inside an installed package and gate it.

    python3 -m release.package_selftest <installed-package-root> --withheld <withheld.json> --out <result.json>

The package ships the Producer engine's tests but withholds the maintainer's
retained qualification evidence and the container build inputs. A test that
verifies withheld evidence cannot pass inside the package. It is tolerated only
when BOTH hold:

1. the test is declared below with the reason its input is not a product input
   (runtime reachability recorded per entry), and
2. its failure is exactly a missing-file error naming a path that this build's
   withheld manifest lists.

Every other failure or error fails the gate. Declared tests that pass are
reported. Nothing is skipped: every test runs.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

# test-id prefix → why its input is not read by any buyer workflow
DEV_EVIDENCE: dict[str, str] = {
    "test_comp_rate_matrix.": "retained HyperFrames rate matrix; read only by the maintainer's comp_rate_oci tooling",
    "test_current_system_inventory_check.": "retained system inventory; read only by the maintainer checker "
                                            "current_system_inventory_check.py",
    "test_graphics_runtime_closure.GraphicsRuntimeClosureTests.test_image_build_includes_all_observer_modules":
        "container image build inputs (templates/motion/.dockerignore); the Mac package has no container route",
    "test_p0_adversarial_ingress_artifact.": "retained hostile-ingress evidence (regenerated by the maintainer's "
                                             "live_p0_adversarial_ingress_acceptance.py)",
    "test_p0_render_effect_parity_artifact.": "retained render-parity evidence root (local, ~21 GB)",
    "test_p2_row1_claim_artifact.": "retained P2 claim cohort evidence",
    "test_p2_visual_lip_sync_artifact.": "retained lip-sync evidence under scripts/producer/artifacts",
    "test_p4_exit_closure_artifact.": "retained P4 live exit-closure evidence",
    "test_p5_compositor_artifact.": "retained P5 compositor evidence",
    "test_p5_review_repair_artifact.": "retained P5 review-repair evidence",
    "test_render_layout_transport.": "container layout observer (templates/motion/container); reachable only through "
                                     "the container-only guided opening/body path, which refuses on the Mac package",
    "test_scene_brief_matrix.": "retained P4 scene-brief matrix evidence",
}
_MISSING = re.compile(r"No such file or directory: '([^']+)'|retained parity evidence root is unavailable")

_RUNNER = r"""
import json, os, sys, traceback, unittest
tests = os.path.join(os.getcwd(), "tests"); sys.path.insert(0, tests); sys.path.insert(0, os.getcwd())
class Result(unittest.TextTestResult):
    rows = []
    def _row(self, test, outcome, err=None):
        text = "".join(traceback.format_exception(*err)) if err else ""
        Result.rows.append({"id": test.id(), "outcome": outcome, "detail": text[-4000:]})
    def addSuccess(self, test): super().addSuccess(test); self._row(test, "pass")
    def addFailure(self, test, err): super().addFailure(test, err); self._row(test, "fail", err)
    def addError(self, test, err): super().addError(test, err); self._row(test, "error", err)
    def addSkip(self, test, reason): super().addSkip(test, reason); Result.rows.append({"id": test.id(), "outcome": "skip", "detail": reason})
suite = unittest.TestLoader().discover(start_dir=tests, top_level_dir=tests, pattern="test_*.py")
unittest.TextTestRunner(verbosity=1, resultclass=Result, stream=sys.stderr).run(suite)
json.dump(Result.rows, open(sys.argv[1], "w"))
"""


def _declared(test_id: str) -> str | None:
    """The reason a test's input is development-only, if declared."""
    return next((reason for prefix, reason in DEV_EVIDENCE.items() if test_id.startswith(prefix)), None)


def _withheld_miss(detail: str, package_app: Path, withheld: set[str]) -> bool:
    """Whether the failure is a missing withheld path (or the unavailable local evidence root)."""
    for match in _MISSING.finditer(detail):
        if match.group(1) is None:
            return True
        path = Path(match.group(1))
        try:
            relative = path.resolve(strict=False).relative_to(package_app.resolve()).as_posix()
        except ValueError:
            continue
        if relative in withheld or any(relative.startswith(entry.rstrip("/") + "/") for entry in withheld):
            return True
    return False


def classify(rows: list[dict], package_app: Path, withheld: set[str]) -> dict:
    """Split results into passes, tolerated withheld-evidence failures and gate failures."""
    tolerated, failures = [], []
    for row in rows:
        if row["outcome"] not in ("fail", "error"):
            continue
        reason = _declared(row["id"])
        if reason and _withheld_miss(row["detail"], package_app, withheld):
            tolerated.append({"id": row["id"], "reason": reason})
        else:
            failures.append({"id": row["id"], "outcome": row["outcome"], "detail": row["detail"][-1200:]})
    counts = {key: sum(row["outcome"] == key for row in rows) for key in ("pass", "fail", "error", "skip")}
    return {"counts": counts, "total": len(rows), "toleratedWithheldEvidence": tolerated,
            "gateFailures": failures, "passed": not failures and counts["pass"] > 0}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("package", type=Path, help="installed package root (contains app/ and app/.venv)")
    parser.add_argument("--withheld", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)
    app = args.package / "app"
    python = app / ".venv" / "bin" / "python3"
    raw = args.out.with_suffix(".rows.json")
    subprocess.run([str(python), "-B", "-c", _RUNNER, str(raw.resolve())], cwd=app / "scripts" / "producer",
                   env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}, check=False)
    rows = json.loads(raw.read_text(encoding="utf-8"))
    withheld = {row["path"] for row in json.loads(args.withheld.read_text(encoding="utf-8"))}
    result = classify(rows, app, withheld)
    args.out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({key: result[key] for key in ("counts", "total", "passed")}))
    for row in result["gateFailures"]:
        print(f"GATE FAILURE {row['outcome']}: {row['id']}", file=sys.stderr)
    return 0 if result["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
