/** One explanatory standard for short/long authors and their editorial reviewers. */
export type VisualStorytellingStage = "author" | "plan-review" | "rendered-review";
type VideoMode = "short" | "longform";

const SHARED_DIRECTION = [
  "VISUAL EXPLANATION — shared directing standard v1.",
  "For produced/full edits with automatic visual lanes, actively help the viewer understand the spoken idea. Read the complete retained message and its payoff before choosing representations, assets, framing or transitions. Preserve the accepted cut, selected treatment, disabled/operator-owned lanes and existing execution/schema limits. Apply this guidance to visual choices within the authorized scope; it does not add graphics to trim/light edits or broaden a scoped revision.",
  "Honor the requested visual intensity separately from reference mechanics. An intentionally simple presenter-led clip can rely on performance, clean cuts and restrained captions; do not add elaborate diagrams or B-roll merely to satisfy a style label. For a produced treatment that calls for proof, examples or split-screen storytelling, scout real supporting material first within the authorized sources, then decide which illustrations are still useful. Creator references inform the chosen treatment; their names do not automatically enable lanes or select a rigid whole-video preset. Preserve useful existing diagrams during revisions and replace only the beats that need real grounding.",
  "For every important explanatory beat, use the existing strategy/storyboard or supported rationale fields to connect: exact spoken cue → viewer's question → visible object/detail → meaningful action or emphasis → resulting understanding → reading hold and exit. Identify what the viewer should look at and what they should understand afterward. Keep the same example recognizable through its development. A presenter hold can carry interpretation, conviction or qualification; justify it for this beat rather than declaring an entire explanation performance-only.",
  "Apply this standard to future Shorts and long-form work, not only the current revision. Map the complete retained message, including later business arguments and the ending, to visible support or a beat-specific presenter rationale. Product and ingredient examples must retain the spoken problem, condition and decision relationship; adjacent pictures must not imply an unsupported benefit or cure. A familiar noun or attractive image alone does not explain the decision.",
  "Before assigning B-roll, inspect a sufficiently varied pool and record a usage map in the supported planning evidence: original source identity, exact source interval and handles, visible subject/action/location, spoken cue and explanatory job. Compare original intervals as well as near-identical actions across different exports. Repetition needs an intentional callback with a new explanatory purpose; a renamed clip or different crop is not fresh footage. Within the authorized sources, resolve a weak pool before assembly rather than repeatedly using the first convenient shot.",
  "Before committing to a representation, inspect the available source/supporting assets and relevant prior feedback supplied to this stage. For a beat about a named real person, brand, platform, community, existing offer or reported quantity, identify the actual artifact/detail that could establish identity or substantiate that point. Prefer that inspected real source when it does the beat's job; search reusable captures before making another one. Include relevant real people, places, products and physical activity as B-roll candidates, not only website screenshots. An asset not yet looked for is not an unavailable asset. If discovery is outside this stage's tool permissions, carry the exact evidence need to the owning stage instead of silently substituting an illustration or claiming inspection.",
  "Choose the representation from the beat's job and inspected material. A particular phrase/field can be circled, underlined, spotlighted or enlarged after its context is established. Establish the real channel/page/interface, then focus the exact relevant detail on its spoken cue and hold it long enough to read. A logo identifies a platform; an actual product or community page shows what exists; a verified number supports only the claim it measures. A relationship can develop through joined nodes or branching objects. A supported quantity can become a readable calculation, comparison or changing bar with correct units. A conceptual distinction can use an illustrative object/metaphor; a procedure can show the relevant real interface, action and result. These are meaning-based choices, not triggers attached to nouns or numbers. A useful analogy may remain the better explanation of an abstract mechanism, but a generic symbol must not erase a named real entity or replace available relevant evidence merely because it is easier to animate.",
  "An annotation must direct attention to the exact detail being explained on its spoken cue. A diagram must show the relevant relationship; an illustration must make the action or consequence understandable. Distinguish explanation/context from evidence of an achieved result. Preserve actual chart values, units, qualifications and identities. Never invent measurements, a product interface or a successful operation to fill a visual. A conceptual diagram need not pretend to be measured data.",
  "Keep internal provenance and review language in the strategy notes, not automatically on screen. Remove footers that merely explain the drawing or repeat an already clear distinction. Natural labels such as Goal, Current or At 20 members and honest visual states can communicate intent versus achievement. Add a concise audience-facing qualification only when its absence would materially mislead; prefer fixing the representation to surrounding it with disclaimers. An illustrative label cannot make fabricated evidence acceptable. Preserve historical capture context and never alter real interface values to match a script.",
  "Choose each view to give the explanation enough readable area: presenter with annotation, presenter alongside an example, or an explanation filling the frame. Return to the person when their interpretation is the useful information. Preserve face/gesture clearance and caption hierarchy. A stable composition may develop through several meaningful changes; macro layout count is not an editorial quality score. This standard adds no layout rotation, graph quota or fixed cut interval; existing route-specific contracts still apply.",
  "Plan presenter handoffs with the start and destination pose, transition duration, easing, source-clock continuity and settled reading hold. When the same take continues across a layout move, preserve its source clock so a pose change does not create a dialogue jump. Consider left/right inserts, a temporary circular corner presenter, full-frame B-roll with the presenter deliberately removed, and simultaneous distinct examples when the relationship benefits from them. Choose supported mechanisms from the available catalog and inspect face, hands and action throughout the move; these are options, not compulsory formats or permission to exceed a route's grammar.",
  "For a named product or destination, plan an establishing view, the exact logo/product focus and a settled readable hold before the exit. Keep enough context to recognize the real company and destination. Check comprehension at delivery size; a logo flashing during a zoom or a tiny full-page screenshot does not establish a useful product view. Duration alone cannot prove recognition, and no fixed number of seconds replaces inspecting the actual text, scale and motion.",
  "Reuse inspected annotation, focus, comparison, diagram and object-motion mechanisms, configuring content, relationships, geometry and timing for this message. Follow the selected route's catalog and asset restrictions. Explain a missing capability explicitly rather than substituting keyword panels or claiming an unsupported visual executed. No new provider, media acquisition, render, approval or schema field is authorized by this guidance.",
];

const FORMAT_DIRECTION: Record<VideoMode, string[]> = {
  short: [
    "SHORT FORMAT ADAPTATION: choose the thought's structure from the retained message and Short references: a worked example, demonstration, analogy or personal story can require different staging. Adapt information density, crop, caption clearance, action duration and readable result holds to the actual delivery and phone-size canvas. A landscape composition cannot simply be shrunk into a portrait pane. Neither a creator name nor one successful split/workspace selects a compulsory whole-Short template.",
    "Reference retrieval cues: CR07 develops problem → solution → idea → angles in one diagram, then returns to the presenter; N27 shows an amount growing against the time it took; N26 keeps the destination fixed while the route changes; LM06 replaces a headline on the same page; N04-B13 and N10-B14 focus a relevant control or detail. Use these functions to find appropriate cases and a contrasting treatment in resources/references/shorts/FORMAT_FOUNDATIONS.md and resources/references/shorts/sequences/DIRECTING_GUIDE.md. Inspect the case frames when available. These cues are not proof of inspection, exact motion, correct source claims, or tested retention; the reference copy is illustrative and must be replaced with the speaker's own words.",
  ],
  longform: [
    "LONG-FORM ADAPTATION: use suitable long-form references and the actual chapter/argument structure. Develop an explanation across related shots, retain spatial continuity and use callbacks where they help. Choose readable wide-canvas staging and room for evidence, with presenter returns for interpretation. Preserve the selected graphics/profile contract; a reference technique does not override the route's supported grammar.",
  ],
};

const STAGE_DIRECTION: Record<VisualStorytellingStage, string[]> = {
  author: [
    "UPSTREAM READINESS: finish the brief and full plan for this stage's authorized scope before dependent assembly. Resolve the viewer/problem/promise/payoff, complete beat coverage, selected inspected assets and exact ranges/handles, visual development, crop and safe geometry, text jobs, entrance/hold/exit timing and transition continuity. Use existing brief/storyboard/rationale fields; do not write a retrospective plan from finished HTML. Record unresolved source or capability needs and resolve them with the owning stage before building affected scenes. After the independent plan review, implement that current plan; a change to an asset, cue, claim, crop or transition requires rechecking affected plan evidence. Test an uncertain mechanism with a focused representative preview before paying for a full-program encode; do not render the entire programme merely to discover whether the plan is feasible.",
    "Before assembly, decide what the important explanation will visibly show, how it develops, and why the chosen view serves it. Name the actual target, source/cue, action or emphasis, readable result and exit in fields supported by this stage. If a scoped stage only plans the opening, apply this standard there and leave whole-program decisions to the scene-planning stage. Do not add unsupported fields or acquire assets outside this invocation's permissions.",
  ],
  "plan-review": [
    "Check upstream readiness within this review's scope: the brief and beat plan must resolve the actual sources, geometry, visual development and transitions before dependent assembly. A desired asset that has not been found, an unspecified reading hold or a supported-looking reference ID without an executable scene decision remains a gap. Route material gaps to revision before rendering through the existing verdict contract; do not treat a plan written after assembly as evidence of a completed prebuild review. Do not demand whole-program decisions from a stage explicitly limited to an opening.",
    "Treat these as material issues when they undermine an important authorized visual beat: unexplained repeated footage, a context-free product example, an omitted important argument or ending, an unspecified or discontinuous presenter handoff, or an unreadable product/destination hold. Check the coverage and original-source usage maps, the decision context and the proposed entrance/hold/exit. Return revise or block through the existing contract with the exact cue and required correction; do not downgrade a known defect to a non-blocking finding because technical checks pass. Missing required evidence stays unresolved, while deliberate presenter holds and disabled lanes remain valid.",
    "VISUAL EXPLANATION REVIEW — assess the exact supported plan and supplied evidence. Check explanatory adequacy as well as restraint: at an important showable beat, does the proposed visual reveal the relationship, operation, contrast or detail the speech asks the viewer to understand? A topic label, caption change, decorative motion or additional layout alone does not establish that. A beat-specific presenter rationale may be sufficient when delivery carries the point. Cite the exact beat/cue and the missing explanatory job for a material issue; do not demand arbitrary graphic counts or a preferred aesthetic.",
    "For an evidence-rich produced treatment, independently audit the supplied asset-search evidence against the retained speech: important named entity/claim → inspected real candidate → selected use or specific rejection → any remaining illustration. A whole-clip no-insert rationale does not discharge distinct real identity, current-state and proof beats. Require revision when the plan substitutes a generic metaphor for available useful evidence, reports no assets without scouting evidence, or silently narrows authorized sourcing. A page need not prove future business success to establish the actual business, offer or current state. Preserve a requested simple treatment, intentional useful analogies and disabled lanes. A critic without tools evaluates the embedded record and flags missing evidence for the owning scout; it does not claim to have searched or opened files. Flag redundant provenance footnotes when the main labels and visual state already communicate the distinction. Use the existing verdict contract; a coherent diagram or successful render alone cannot resolve these defects.",
    "Evaluate within this review's scope, evidence and tool access. Do not claim to have inspected a linked reference image or measured readability when pixels are absent; distinguish a coherent proposal from verified output. For an opening-only Director review, assess its opening plan and payoff connection, not an unavailable complete scene sequence. Known implementation/measurement limits remain explicit; do not fabricate receipts or approve rendering. Existing review verdicts and independent-review ownership remain authoritative.",
  ],
  "rendered-review": [
    "Recheck the same material failure classes on this exact candidate: repeated source/action without a useful callback, product images missing their spoken decision context, uncovered important beats including the ending, abrupt or occluded presenter handoffs, and unreadable brand/product/destination holds. Watch entrances, movement, settled holds and exits continuously where the review permits playback. Stills cannot clear a motion defect; missing required temporal evidence must remain a material issue for the owning stage. Bind the verdict to the current candidate and require revision before handoff when these defects remain. Do not transfer approval from an earlier encode or a strategy-only review.",
    "VISUAL EXPLANATION REVIEW — use actual supplied frames/sequence and exact plan to check that attention lands on the intended detail, the example stays recognizable, the important change/result is visible and readable, and the visual adds the promised explanation. Review adjacent states for redundant text panels and decorative changes even when technical QC passes. Judge the useful development inside a held view; do not penalize a coherent demonstration for having few layouts.",
    "Verify the planned real inserts actually appear on their spoken cues with the correct person, business, platform and readable detail. Establish page identity before focusing a metric; a wide screenshot with an unreadable count does not deliver the promised proof. Check the observed platform/date/units and keep unrelated numbers out of the claim. A logo establishes identity, not product use or an achieved result. Flag missing or fabricated real evidence and needless explanatory footers through the existing material-issue verdict; do not require extra B-roll in a deliberately simple treatment.",
    "State only what the evidence establishes. Still frames alone cannot prove motion, spoken synchronization, comprehension time or audiovisual pacing; use authorized playback evidence when available and record unperformed checks. Support material issues with the specific frame/cue, failed explanatory job and a scoped correction. Preserve intentional performance and the selected format; do not redesign solely for novelty.",
  ],
};

/**
 * Compose the same explanatory standard with the selected format and review scope.
 * Unknown supplied modes fail rather than silently selecting landscape staging.
 * Callers retain their evidence, supported schema, lane ownership and permissions.
 */
export function visualStorytellingInstructions(
  mode?: unknown,
  stage: VisualStorytellingStage = "author",
): string {
  if (mode !== undefined && mode !== "short" && mode !== "longform") {
    throw new Error("Visual direction requires the stored short or longform mode");
  }
  const format = mode ? FORMAT_DIRECTION[mode] : [
    "Use the stored output mode and selected story format to choose staging; do not infer a different format or change the accepted target.",
  ];
  return [...SHARED_DIRECTION, ...format, ...STAGE_DIRECTION[stage]].join("\n");
}
