#!/usr/bin/env python3
"""captions — burned karaoke/line captions (ASS) from output-time words.

Stage 3 of the PRODUCER renderer (see docs/producer/PRODUCER_PLAN.md §4.2). Captions are
NEVER brain-authored: they derive deterministically from the kept words, which
arrive ALREADY REMAPPED to OUTPUT time by ``compile_timeline.remap_words`` — so
karaoke timing survives cuts + per-range speed changes with no divergence from
what is actually said. This module only groups, lightly normalizes (verbatim,
no paraphrase), and lays the words out as an ASS subtitle track.

Three styles: ``karaoke`` (fill-from-left highlight), ``line`` (plain multi-word
blocks), and ``minimal`` (reference study R1/R2 — one word, or a <=3-word phrase
when words nearly touch, per event; chest-anchored; two-tone gold serif-italic
accents on ``captions.emphasisWords``). karaoke/line share the block grouping
below; minimal lives in the sibling ``captions_minimal`` module (``build_ass``
dispatches there, reusing this module's ASS primitives).

Grouping (karaoke/line) respects ``producer_config.CAPTIONS``: <=max_lines/block,
<=max_chars_per_line (a COUPLED pair with font_size — see the config comment;
edge X10), block word-span clamped to ``block_s`` (never mid-word), a new
block on phrase gaps > ``gap_split_s``, and a words/sec ceiling that splits
dense bursts into the small TikTok-style blocks a viewer can actually read.

Placement math (documented once): the style is bottom-center (ASS alignment 2)
with ``MarginV = CANVAS.height - CAPTIONS.baseline_max_y = 1920 - 1340 = 580``.
libass lands the bottom edge of the lowest line at ``PlayResY - MarginV = 1340``
(= ``baseline_max_y``), so 1-2 line blocks sit inside the y_band [1150, 1340] and
clear of the safe-box bottom edge (y = 1920 - 520 = 1400). MarginL/MarginR come
from the safe box (60 / 150); centering inside [60, 930] puts caption text on the
right-rail-corrected visual center x=495.

CLI: captions.py <words.json> <out.ass> [--style karaoke|line|minimal]
                 [--emphasis word1,word2]
  words.json = [{"word": str, "start": float, "end": float}, ...] in OUTPUT time.
"""

from __future__ import annotations

import json
import re
import sys

import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # run-by-path: producer pkg root on sys.path
from producer_config import (CANVAS, CANVAS_BY_ASPECT, CAPTION_LAYOUT_BY_ASPECT,
                             CAPTIONS, SAFE_BOX)

# Layout heuristic (not a delivery spec). gap_split_s + hang_s are centralized
# tunables in producer_config.CAPTIONS; this is the only local grouping knob.
_MIN_WPS_SPLIT_WORDS = 3  # only the wps ceiling splits a block once it has >= this

# Sentence-aware capitalization: a block's first word is capitalized ONLY at a
# real sentence start — the first block, or one following a block that ended in
# terminal punctuation. Everything else stays verbatim (no mid-sentence caps).
_TERMINAL = {".", "!", "?", "…"}
_CLOSERS = "\"')]}’”»"

_PUNCT = set(",.!?;:)]}’”")   # trailing punctuation that hugs its word
_WS_RE = re.compile(r"\s+")
_NAMED_COLORS = {"white": "FFFFFF", "black": "000000",
                 "yellow": "FFFF00", "red": "FF0000"}

# Shared ASS document shell (one source of truth for every style's header). PlayRes
# MUST match the delivery frame — a mismatch makes libass scale the whole subtitle
# canvas onto the video, which is exactly how a 9:16 PlayRes threw 16:9 captions to
# mid-chest. Keyed on the render canvas (9:16 default for back-compat).
def _script_info(canvas: dict = CANVAS) -> list[str]:
    return [
        "[Script Info]",
        "; PRODUCER burned captions — generated by captions.py",
        "ScriptType: v4.00+",
        f"PlayResX: {canvas['width']}",
        f"PlayResY: {canvas['height']}",
        "WrapStyle: 2",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        "",
    ]
_STYLE_FORMAT = (
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
    "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
    "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
    "Alignment, MarginL, MarginR, MarginV, Encoding"
)
_EVENT_FORMAT = (
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
    "Effect, Text"
)


# ---------------------------------------------------------------------------
# Text normalization (verbatim — light artifact cleanup only, no paraphrase)
# ---------------------------------------------------------------------------
def _norm_word(text: str) -> str:
    """Collapse stray whitespace inside a token. Deepgram smart_format already
    emits currency/numerals ("$12k", "40%"), so we do not reformat numbers."""
    return _WS_RE.sub(" ", str(text)).strip()


def _merge_punctuation(words: list[dict]) -> list[dict]:
    """Attach a pure-punctuation token to the previous word.

    Fixes "space before punctuation" at the source (a " ," would otherwise
    render as a lone karaoke syllable). Purely mechanical — never changes what
    is said, only how a stray punctuation token joins its neighbour.
    """
    out: list[dict] = []
    for w in words:
        text = _norm_word(w.get("word", ""))
        if out and text and all(ch in _PUNCT for ch in text):
            out[-1]["word"] = f"{out[-1]['word']}{text}"
            out[-1]["end"] = float(w.get("end", out[-1]["end"]))
        elif text:
            out.append({"word": text,
                        "start": float(w["start"]),
                        "end": float(w["end"])})
    return out


def _capitalize_first(text: str) -> str:
    """Uppercase the first alphabetic char."""
    for i, ch in enumerate(text):
        if ch.isalpha():
            return text[:i] + ch.upper() + text[i + 1:]
    return text


def _ends_sentence(word: str) -> bool:
    """True if a word closes a sentence (terminal punct, ignoring closing quotes)."""
    trimmed = _norm_word(word).rstrip(_CLOSERS)
    return bool(trimmed) and trimmed[-1] in _TERMINAL


def _display_texts(block: list[dict], capitalize_first: bool) -> list[str]:
    """Per-word render strings: normalized; the first word is capitalized only
    when it opens a sentence (see ``_block_caps``)."""
    texts = [_norm_word(w["word"]) for w in block]
    if texts and capitalize_first:
        texts[0] = _capitalize_first(texts[0])
    return texts


def _escape_ass(text: str) -> str:
    """Escape ASS override-block specials so verbatim text renders literally."""
    return (text.replace("\\", "").replace("{", "\\{")
            .replace("}", "\\}").replace("\n", " "))


# ---------------------------------------------------------------------------
# Line wrapping + block grouping
# ---------------------------------------------------------------------------
def _wrap_indices(texts: list[str], max_chars: int) -> list[list[int]]:
    """Greedy word wrap → list of lines, each a list of word indices."""
    lines: list[list[int]] = []
    cur: list[int] = []
    width = 0
    for i, t in enumerate(texts):
        add = len(t) + (1 if cur else 0)
        if cur and width + add > max_chars:
            lines.append(cur)
            cur, width = [i], len(t)
        else:
            cur.append(i)
            width += add
    if cur:
        lines.append(cur)
    return lines


def _line_widths(texts: list[str], lines: list[list[int]]) -> list[int]:
    return [sum(len(texts[i]) for i in ln) + max(0, len(ln) - 1) for ln in lines]


def _fits_block(block: list[dict], cfg: dict) -> bool:
    """True if the block wraps into <= max_lines each <= max_chars_per_line."""
    texts = [_norm_word(w["word"]) for w in block]
    lines = _wrap_indices(texts, cfg["max_chars_per_line"])
    if len(lines) > cfg["max_lines"]:
        return False
    return all(w <= cfg["max_chars_per_line"] for w in _line_widths(texts, lines))


def _wps_over(block: list[dict], cfg: dict) -> bool:
    """True if this many words in this span exceeds the reading-pace ceiling."""
    span = float(block[-1]["end"]) - float(block[0]["start"])
    return (len(block) >= _MIN_WPS_SPLIT_WORDS and span > 0
            and len(block) / span > cfg["words_per_sec_max"])


def _split_oversized(words: list[dict], max_chars: int) -> list[dict]:
    """Hard-split any single token wider than one caption line.

    A token longer than ``max_chars`` (URL, long numeral) cannot wrap, so
    libass would render it past the safe width — the single-word case of edge
    X10. Pieces get a trailing hyphen and share the word's time span
    proportionally so karaoke timing stays monotonic.
    """
    out: list[dict] = []
    for w in words:
        text = str(w["word"])
        if len(text) <= max_chars:
            out.append(w)
            continue
        step = max_chars - 1
        pieces = [text[i:i + step] for i in range(0, len(text), step)]
        start, end = float(w["start"]), float(w["end"])
        per_char = (end - start) / len(text)
        cursor = start
        for i, piece in enumerate(pieces):
            p_end = cursor + per_char * len(piece)
            suffix = "-" if i < len(pieces) - 1 else ""
            out.append({**w, "word": piece + suffix,
                        "start": round(cursor, 4), "end": round(p_end, 4)})
            cursor = p_end
    return out


def group_words(words: list[dict], cfg: dict = CAPTIONS) -> list[list[dict]]:
    """Greedy fill into caption blocks under every CAPTIONS limit.

    A block closes (before the offending word) on any of: a phrase gap
    > ``gap_split_s``, a wrap that would need more lines/chars than config
    allows, a word-span past ``block_s`` max (never cutting a word), or the
    words/sec ceiling. Oversized single tokens are pre-split (see
    ``_split_oversized``).
    """
    words = _split_oversized(words, cfg["max_chars_per_line"])
    blocks: list[list[dict]] = []
    cur: list[dict] = []
    span_max = cfg["block_s"][1]
    gap_split = cfg["gap_split_s"]
    for w in words:
        if not cur:
            cur = [w]
            continue
        gap = float(w["start"]) - float(cur[-1]["end"])
        cand = cur + [w]
        span = float(w["end"]) - float(cur[0]["start"])
        if (gap > gap_split or not _fits_block(cand, cfg)
                or span > span_max or _wps_over(cand, cfg)):
            blocks.append(cur)
            cur = [w]
        else:
            cur.append(w)
    if cur:
        blocks.append(cur)
    return blocks


def _block_windows(blocks: list[list[dict]], cfg: dict) -> list[tuple[float, float]]:
    """Display (start, end) per block: first word start → min(last end + hang,
    next block start), capped at block_max_s, floored so end > start."""
    out: list[tuple[float, float]] = []
    for i, b in enumerate(blocks):
        start = float(b[0]["start"])
        end = float(b[-1]["end"]) + cfg["hang_s"]
        if i + 1 < len(blocks):
            end = min(end, float(blocks[i + 1][0]["start"]))
        end = min(end, start + cfg["block_max_s"])
        if end <= start:
            end = start + min(cfg["block_min_s"], cfg["block_max_s"])
        out.append((round(start, 3), round(end, 3)))
    return out


# ---------------------------------------------------------------------------
# ASS emission — colours, time, karaoke timing, dialogue text
# ---------------------------------------------------------------------------
def ass_color(spec: str) -> str:
    """Map a name or '#RRGGBB' to the ASS &HAABBGGRR literal (opaque)."""
    raw = str(spec).strip().lstrip("#")
    hexs = _NAMED_COLORS.get(raw.lower(), raw)
    if len(hexs) != 6:
        raise ValueError(f"bad colour {spec!r}")
    rr, gg, bb = hexs[0:2], hexs[2:4], hexs[4:6]
    return f"&H00{bb}{gg}{rr}".upper()


def _ass_time(t: float) -> str:
    """Seconds → ASS H:MM:SS.CC (centisecond precision)."""
    cs = max(0, int(round(t * 100)))
    h, cs = divmod(cs, 360000)
    m, cs = divmod(cs, 6000)
    s, cs = divmod(cs, 100)
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _karaoke_cs(block: list[dict]) -> list[int]:
    """Per-word \\k durations (centiseconds), cumulative-rounded so the highlight
    sweep tracks word onsets without drift. Word i turns from SecondaryColour
    (highlight) to PrimaryColour (fill) when word i+1 begins — a clean
    fill-from-left karaoke where the leading highlighted word is the current one.
    """
    start0 = float(block[0]["start"])
    switches: list[float] = []
    prev = 0.0
    for i, w in enumerate(block):
        raw = (float(block[i + 1]["start"]) if i + 1 < len(block)
               else float(w["end"])) - start0
        prev = max(prev, raw)          # keep monotonic under overlaps
        switches.append(prev)
    durs: list[int] = []
    prev_cs = 0
    for sw in switches:
        cs = int(round(sw * 100))
        durs.append(max(0, cs - prev_cs))
        prev_cs = cs
    return durs


def _render_karaoke(block: list[dict], cfg: dict, capitalize_first: bool) -> str:
    texts = _display_texts(block, capitalize_first)
    durs = _karaoke_cs(block)
    lines = _wrap_indices(texts, cfg["max_chars_per_line"])
    rendered = [" ".join(f"{{\\k{durs[i]}}}{_escape_ass(texts[i])}" for i in ln)
                for ln in lines]
    return "\\N".join(rendered)


def _render_line(block: list[dict], cfg: dict, capitalize_first: bool) -> str:
    texts = _display_texts(block, capitalize_first)
    lines = _wrap_indices(texts, cfg["max_chars_per_line"])
    return "\\N".join(" ".join(_escape_ass(texts[i]) for i in ln) for ln in lines)


def _margin_v(cfg: dict = CAPTIONS) -> int:
    """Bottom margin that lands the block's bottom edge at baseline_max_y.

    Takes ``cfg`` so per-plan band shifts (edge C12: dodge a source's own
    lower-third) AND the aspect canvas actually reach the ASS — reading the module
    global here would silently ignore the override and re-introduce the 16:9 bug.
    """
    return cfg.get("canvas", CANVAS)["height"] - cfg["baseline_max_y"]


def _document(style_lines: list[str], event_lines: list[str],
              canvas: dict = CANVAS) -> str:
    """Assemble a complete ASS doc from its style + event blocks.

    The single shell every style shares (script-info header, the V4+ style +
    event Format lines, then the styles and dialogues). Keeps the header bytes
    identical across karaoke/line/minimal — only ``style_lines`` differ. ``canvas``
    sets PlayRes (9:16 default so the minimal style + any legacy caller is unchanged).
    """
    head = "\n".join([
        *_script_info(canvas),
        "[V4+ Styles]",
        _STYLE_FORMAT,
        *style_lines,
        "",
        "[Events]",
        _EVENT_FORMAT,
    ])
    return head + "\n" + "\n".join(event_lines) + "\n"


def _caption_style(cfg: dict = CAPTIONS) -> str:
    """The single 'Caption' style line for the karaoke/line block styles."""
    st = cfg["style"]
    return (
        "Style: Caption,{font},{size},{pri},{sec},{outl},&H00000000,"
        "-1,0,0,0,100,100,0,0,1,{opx},0,2,{ml},{mr},{mv},1"
    ).format(font=cfg["font"], size=cfg["font_size"],
             pri=ass_color(st["fill"]), sec=ass_color(st["karaoke_highlight"]),
             outl=ass_color(st["outline"]), opx=st["outline_px"],
             ml=cfg.get("margin_l", SAFE_BOX["left"]),
             mr=cfg.get("margin_r", SAFE_BOX["right"]), mv=_margin_v(cfg))


def _block_caps(blocks: list[list[dict]]) -> list[bool]:
    """Per block: capitalize its first word only at a sentence start — the first
    block, or one whose predecessor ended in terminal punctuation."""
    return [i == 0 or _ends_sentence(blocks[i - 1][-1]["word"])
            for i in range(len(blocks))]


def caption_cfg_for_aspect(aspect: str, base: dict = CAPTIONS) -> dict:
    """``CAPTIONS`` merged with the aspect's layout (baseline/margins/font) + its
    delivery ``canvas``, so ``build_ass`` positions captions for the ACTUAL frame.
    Unknown aspect falls back to 9:16 (the historical default). This is the seam
    that fixed the 16:9 mid-chest bug — render.py builds the cfg through here."""
    layout = CAPTION_LAYOUT_BY_ASPECT.get(aspect, CAPTION_LAYOUT_BY_ASPECT["9:16"])
    canvas = CANVAS_BY_ASPECT.get(aspect, CANVAS)
    return {**base, **layout, "canvas": canvas}


def build_ass(words: list[dict], style: str = "karaoke",
              cfg: dict = CAPTIONS) -> str:
    """Compile output-time words into a complete ASS document string."""
    if style == "minimal":
        # Lazy import breaks the captions <-> captions_minimal cycle: the
        # minimal module reuses this module's ASS primitives at import time.
        from captions.captions_minimal import build_minimal
        return build_minimal(words, cfg)
    if style == "whisper":
        # Jaden base layer (G2) — same lazy-import shape as minimal.
        from captions.captions_whisper import build_whisper
        return build_whisper(words, cfg)
    if style not in ("karaoke", "line"):
        raise ValueError(
            f"style must be karaoke|line|minimal|whisper (got {style!r})")
    clean = _merge_punctuation(words)
    blocks = group_words(clean, cfg)
    windows = _block_windows(blocks, cfg)
    caps = _block_caps(blocks)
    render = _render_karaoke if style == "karaoke" else _render_line
    events = [
        f"Dialogue: 0,{_ass_time(s)},{_ass_time(e)},Caption,,0,0,0,,"
        f"{render(b, cfg, cap)}"
        for b, (s, e), cap in zip(blocks, windows, caps)
    ]
    return _document([_caption_style(cfg)], events, cfg.get("canvas", CANVAS))


def _pop_opt(args: list[str], flag: str, default: str = "") -> str:
    """Pop ``flag <value>`` out of ``args`` in place, returning value/default."""
    if flag not in args:
        return default
    idx = args.index(flag)
    value = args[idx + 1] if idx + 1 < len(args) else default
    del args[idx:idx + 2]
    return value


def main() -> None:
    args = sys.argv[1:]
    style = _pop_opt(args, "--style", "karaoke")
    emphasis = [w for w in _pop_opt(args, "--emphasis").split(",") if w]
    if len(args) != 2:
        print(json.dumps({"error": "Usage: captions.py <words.json> <out.ass> "
                                    "[--style karaoke|line|minimal|whisper] "
                                    "[--emphasis word1,word2]"}))
        sys.exit(1)
    try:
        with open(args[0]) as f:
            words = json.load(f)
        cfg = CAPTIONS
        if emphasis:
            cfg = {**CAPTIONS, "emphasisWords": emphasis}
        ass = build_ass(words, style=style, cfg=cfg)
        with open(args[1], "w") as f:
            f.write(ass)
        if style == "minimal":
            from captions.captions_minimal import event_count
            count, unit = event_count(words, cfg), "events"
        elif style == "whisper":
            from captions.captions_whisper import event_count
            count, unit = event_count(words, cfg), "cues"
        else:
            count = len(group_words(_merge_punctuation(words)))
            unit = "blocks"
        print(json.dumps({"status": "done", "style": style,
                          "words": len(words), unit: count, "out": args[1]}))
    except (OSError, json.JSONDecodeError, ValueError, KeyError) as exc:
        print(json.dumps({"error": str(exc)}))
        sys.exit(1)


if __name__ == "__main__":
    main()
